import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Icon, Button } from "@vayva/ui";
export const DisputeList = ({ disputes, isLoading }) => {
    if (isLoading)
        return (_jsx("div", { className: "py-10 text-center text-gray-400", children: "Loading disputes..." }));
    if (disputes.length === 0) {
        return (_jsxs("div", { className: "text-center py-16 text-gray-400 border border-dashed border-gray-200 rounded-xl bg-gray-50/50", children: [_jsx(Icon, { name: "ShieldCheck", size: 48, className: "mx-auto mb-4 opacity-20" }), _jsx("p", { children: "No active disputes. Your store is healthy!" })] }));
    }
    return (_jsxs("div", { className: "space-y-4", children: [_jsx("div", { className: "flex justify-between items-center bg-red-50 p-4 rounded-xl border border-red-100", children: _jsxs("div", { className: "flex gap-3", children: [_jsx("div", { className: "w-10 h-10 bg-red-100 rounded-full flex items-center justify-center text-red-600 shrink-0", children: _jsx(Icon, { name: "Scale", size: 20 }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-red-900", children: "Action Required" }), _jsx("p", { className: "text-xs text-red-700", children: "Funds for these orders are on hold until resolved." })] })] }) }), _jsx("div", { className: "space-y-3", children: disputes.map((disp) => (_jsxs("div", { className: "bg-white border border-red-100 rounded-xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-4 shadow-sm hover:shadow-md transition-shadow", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx("div", { className: "w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center text-gray-500 shrink-0", children: _jsx(Icon, { name: "AlertTriangle", size: 20 }) }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsxs("span", { className: "font-bold text-gray-900 text-sm", children: ["Order #", disp.orderId.split("_")[1] || disp.orderId] }), _jsxs("span", { className: "text-xs text-gray-500", children: ["\u2022 ", disp.customerName] })] }), _jsx("p", { className: "text-sm font-medium text-red-600", children: disp.reason }), _jsxs("p", { className: "text-xs text-gray-400 mt-1", children: ["Deadline: ", new Date(disp.deadline).toLocaleDateString()] })] })] }), _jsxs("div", { className: "flex items-center gap-6", children: [_jsxs("div", { className: "text-right", children: [_jsx("p", { className: "text-xs text-gray-400 uppercase font-bold", children: "Held Amount" }), _jsx("p", { className: "font-bold font-mono text-lg text-gray-900", children: new Intl.NumberFormat("en-NG", {
                                                style: "currency",
                                                currency: disp.currency,
                                            }).format(disp.amount) })] }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Button, { className: "px-4 py-2 bg-black text-white rounded-lg text-xs font-bold hover:bg-gray-800 transition-colors h-auto", children: "Submit Evidence" }), _jsx(Button, { variant: "outline", className: "px-4 py-2 border border-gray-200 rounded-lg text-xs font-bold text-gray-700 hover:bg-gray-50 transition-colors h-auto", children: "View Details" })] })] })] }, disp.id))) })] }));
};
