import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Icon, Button } from "@vayva/ui";
export const WalletHero = ({ balance, isLoading, onWithdraw, }) => {
    if (isLoading || !balance) {
        return (_jsx("div", { className: "h-[240px] w-full bg-gray-100 animate-pulse rounded-2xl" }));
    }
    const formatCurrency = (amount, currency) => {
        return new Intl.NumberFormat("en-NG", {
            style: "currency",
            currency: currency,
        }).format(amount);
    };
    return (_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-8", children: [_jsxs("div", { className: "md:col-span-2 bg-[#0B0B0B] text-white rounded-2xl p-8 relative overflow-hidden shadow-lg flex flex-col justify-between min-h-[240px]", children: [_jsxs("div", { className: "relative z-10", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2 text-gray-400", children: [_jsx("span", { className: "text-sm font-medium uppercase tracking-wider", children: "Available Balance" }), _jsx(Icon, { name: "Info", size: 14, className: "opacity-50 hover:opacity-100 cursor-help" })] }), _jsx("h1", { className: "font-heading font-bold text-5xl tracking-tight mb-1", children: formatCurrency(balance.available, balance.currency) }), _jsx("p", { className: "text-sm text-gray-500", children: "Funds ready for withdrawal" })] }), _jsxs("div", { className: "relative z-10 flex gap-12 pt-6 border-t border-gray-800 mt-6", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("div", { className: "w-2 h-2 rounded-full bg-yellow-500" }), _jsx("p", { className: "text-xs text-gray-400 font-bold uppercase", children: "Pending" })] }), _jsx("p", { className: "font-medium text-xl", children: formatCurrency(balance.pending, balance.currency) }), _jsx("p", { className: "text-[10px] text-gray-500", children: "Clears in 24-48h" })] }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("div", { className: "w-2 h-2 rounded-full bg-red-500" }), _jsx("p", { className: "text-xs text-gray-400 font-bold uppercase", children: "On Hold" })] }), _jsx("p", { className: "font-medium text-xl text-red-200", children: formatCurrency(balance.blocked, balance.currency) }), _jsx("p", { className: "text-[10px] text-gray-500", children: "Disputes / Refunds" })] })] }), _jsx("div", { className: "absolute top-0 right-0 w-[400px] h-[400px] bg-gradient-to-bl from-gray-800/20 to-transparent rounded-full -mr-32 -mt-32 pointer-events-none blur-3xl" })] }), _jsxs("div", { className: "bg-white border border-gray-200 rounded-2xl p-8 flex flex-col justify-center space-y-4 shadow-sm h-[240px]", children: [_jsxs(Button, { onClick: onWithdraw, className: "w-full py-3 bg-black text-white rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-gray-800 transition-all active:scale-[0.98] h-auto", children: [_jsx(Icon, { name: "ArrowDownLeft", size: 20 }), " Withdraw Funds"] }), _jsxs(Button, { variant: "outline", className: "w-full py-3 bg-white border border-gray-200 text-gray-900 rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-gray-50 transition-all h-auto", children: [_jsx(Icon, { name: "History", size: 20 }), " Payout History"] })] })] }));
};
