import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { X, Trash2, ArrowRight } from "lucide-react";
import { Button } from "@vayva/ui";
export const RFQDrawer = ({ isOpen, onClose, items, onRemoveItem, onUpdateQty, onSubmit, }) => {
    const [submitting, setSubmitting] = useState(false);
    // Simple state for notes
    const [notes, setNotes] = useState("");
    const handleSubmit = () => {
        setSubmitting(true);
        setTimeout(() => {
            setSubmitting(false);
            onSubmit();
        }, 1500);
    };
    if (!isOpen)
        return null;
    return (_jsx("div", { className: "fixed inset-0 z-[100] flex justify-end bg-black/50 backdrop-blur-sm", children: _jsxs("div", { className: "w-full max-w-md bg-white h-full shadow-2xl flex flex-col animate-in slide-in-from-right duration-300", children: [_jsxs("div", { className: "p-6 border-b border-gray-200 bg-[#0F172A] text-white flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "font-bold text-lg", children: "Request For Quote" }), _jsxs("p", { className: "text-xs text-gray-400", children: [items.length, " items ready for pricing review"] })] }), _jsx(Button, { variant: "ghost", size: "icon", onClick: onClose, className: "p-2 hover:bg-white/10 rounded-full transition-colors h-auto text-white hover:text-white", "aria-label": "Close RFQ drawer", children: _jsx(X, { size: 20 }) })] }), _jsxs("div", { className: "flex-1 overflow-y-auto p-6 space-y-6", children: [items.length === 0 ? (_jsxs("div", { className: "text-center text-gray-400 py-12", children: [_jsx("p", { children: "Your RFQ list is empty." }), _jsx(Button, { variant: "link", onClick: onClose, className: "mt-4 text-blue-600 font-bold hover:underline h-auto p-0", "aria-label": "Browse catalog", children: "Browse Catalog" })] })) : (items.map(({ product, qty }) => {
                            const moq = product.wholesaleDetails?.moq || 1;
                            const isMoqMet = qty >= moq;
                            return (_jsxs("div", { className: "flex gap-4 border-b border-gray-100 pb-6", children: [_jsx("div", { className: "w-16 h-16 bg-gray-100 rounded-lg overflow-hidden shrink-0", children: _jsx("img", { src: product.images?.[0], alt: product.name, className: "w-full h-full object-cover" }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h3", { className: "font-bold text-gray-900 truncate", children: product.name }), _jsxs("p", { className: "text-xs text-gray-500 mb-2", children: ["SKU: ", product.id.toUpperCase()] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("label", { htmlFor: `qty-${product.id}`, className: "text-xs font-bold text-gray-500", children: "Qty:" }), _jsx("input", { id: `qty-${product.id}`, type: "number", value: qty, onChange: (e) => onUpdateQty(product.id, parseInt(e.target.value) || 0), className: `w-20 px-2 py-1 border rounded text-sm ${!isMoqMet ? "border-red-300 bg-red-50 text-red-900" : "border-gray-300"}` })] }), _jsx(Button, { variant: "ghost", size: "icon", onClick: () => onRemoveItem(product.id), className: "text-gray-400 hover:text-red-500 h-auto p-1", "aria-label": `Remove ${product.name} from RFQ`, children: _jsx(Trash2, { size: 16 }) })] }), !isMoqMet && (_jsxs("p", { className: "text-[10px] text-red-600 mt-1 font-bold", children: ["Below MOQ (", moq, " units)"] }))] })] }, product.id));
                        })), items.length > 0 && (_jsxs("div", { children: [_jsx("label", { htmlFor: "rfq-notes", className: "block text-sm font-bold text-gray-700 mb-2", children: "Additional Notes / Delivery Terms" }), _jsx("textarea", { id: "rfq-notes", value: notes, onChange: (e) => setNotes(e.target.value), className: "w-full h-32 p-3 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-600", placeholder: "E.g., Special packaging requirements, specific delivery date..." })] }))] }), items.length > 0 && (_jsxs("div", { className: "p-6 border-t border-gray-200 bg-gray-50", children: [_jsxs("div", { className: "flex items-center justify-between mb-4 text-sm", children: [_jsx("span", { className: "text-gray-500", children: "Estimated Total (Indicative)" }), _jsxs("span", { className: "font-bold text-gray-900", children: ["~ \u20A6", items
                                            .reduce((acc, item) => acc + item.product.price * item.qty, 0)
                                            .toLocaleString()] })] }), _jsx(Button, { onClick: handleSubmit, disabled: submitting ||
                                items.some((i) => i.qty < (i.product.wholesaleDetails?.moq || 1)), className: "w-full bg-[#0F172A] hover:bg-[#1E293B] disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold py-4 rounded-lg flex items-center justify-center gap-2 transition-all h-auto", "aria-label": "Submit quote request", children: submitting ? ("Submitting Request...") : (_jsxs(_Fragment, { children: ["Submit Quote Request ", _jsx(ArrowRight, { size: 18 })] })) }), _jsx("p", { className: "text-center text-[10px] text-gray-400 mt-3", children: "This is not a final invoice. You will receive a formal quote within 24 hours." })] }))] }) }));
};
