"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@vayva/ui";
import { isTierAccessible } from "@/lib/templates";
import Link from "next/link";
export const TemplatePreviewModal = ({ template, userTier, onClose, onApply, }) => {
    const isAccessible = isTierAccessible(userTier, template.tier);
    return (_jsx("div", { className: "fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[100] p-4 overflow-y-auto", onClick: onClose, children: _jsx("div", { className: "bg-white rounded-2xl max-w-5xl w-full shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-200", onClick: (e) => e.stopPropagation(), children: _jsxs("div", { className: "flex flex-col lg:flex-row", children: [_jsxs("div", { className: "lg:w-1/2 bg-gray-50 p-8 border-r border-gray-100", children: [_jsx("div", { className: "aspect-video bg-gray-200 rounded-xl mb-8 flex items-center justify-center overflow-hidden border border-gray-200 shadow-inner", children: _jsxs("div", { className: "text-center p-6", children: [_jsx("svg", { className: "w-16 h-16 text-gray-400 mx-auto mb-4", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 1, d: "M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" }) }), _jsxs("p", { className: "text-sm text-gray-500 font-medium", children: [template.name, " Interface Preview"] })] }) }), _jsxs("div", { children: [_jsx("h4", { className: "text-sm font-bold text-gray-900 uppercase tracking-widest mb-4", children: "What it creates" }), _jsxs("div", { className: "grid grid-cols-2 gap-6", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-bold text-gray-400 uppercase mb-2", children: "Pages & Sections" }), _jsx("ul", { className: "space-y-1", children: [
                                                            ...template.creates.pages,
                                                            ...template.creates.sections,
                                                        ].map((item) => (_jsxs("li", { className: "text-sm text-gray-600 flex items-center gap-2", children: [_jsx("span", { className: "w-1 h-1 rounded-full bg-green-500" }), item] }, item))) })] }), _jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-bold text-gray-400 uppercase mb-2", children: "Data Objects" }), _jsx("ul", { className: "space-y-1", children: template.creates.objects.map((item) => (_jsxs("li", { className: "text-sm text-gray-600 flex items-center gap-2", children: [_jsx("span", { className: "w-1 h-1 rounded-full bg-blue-500" }), item] }, item))) })] })] })] })] }), _jsxs("div", { className: "lg:w-1/2 p-10 flex flex-col", children: [_jsxs("div", { className: "flex justify-between items-start mb-6", children: [_jsxs("div", { children: [_jsxs("span", { className: `text-[10px] font-bold uppercase px-2 py-1 rounded ${template.tier === "pro"
                                                    ? "bg-purple-100 text-purple-700"
                                                    : template.tier === "growth"
                                                        ? "bg-green-100 text-green-700"
                                                        : "bg-gray-100 text-gray-600"}`, children: [template.tier === "pro"
                                                        ? "₦40,000"
                                                        : template.tier === "growth"
                                                            ? "₦25,000"
                                                            : "Free", " ", "Plan"] }), _jsx("h2", { className: "text-3xl font-bold text-gray-900 mt-2", children: template.name })] }), _jsx(Button, { variant: "ghost", size: "icon", onClick: onClose, className: "hover:bg-gray-100 rounded-full transition-colors text-gray-400", children: _jsx("svg", { className: "w-6 h-6", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M6 18L18 6M6 6l18 18" }) }) })] }), _jsx("p", { className: "text-gray-600 leading-relaxed mb-8", children: template.description }), _jsx("div", { className: "space-y-6 mb-10 flex-grow", children: _jsxs("div", { children: [_jsx("h4", { className: "text-xs font-bold text-gray-400 uppercase mb-3", children: "Setup logic" }), _jsx("ul", { className: "space-y-2", children: template.configures.slice(0, 3).map((item) => (_jsxs("li", { className: "text-sm text-gray-700 flex items-start gap-3", children: [_jsx("svg", { className: "w-4 h-4 text-green-500 mt-0.5 shrink-0", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M5 13l4 4L19 7" }) }), item] }, item))) })] }) }), _jsxs("div", { className: "pt-6 border-t border-gray-100", children: [isAccessible ? (_jsx(Button, { onClick: () => onApply(template), className: "w-full py-6 text-lg font-bold bg-[#22C55E] hover:bg-[#16A34A] text-white rounded-xl shadow-lg shadow-green-100 transition-all", children: "Apply Template" })) : (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "p-4 bg-orange-50 border border-orange-100 rounded-xl flex items-start gap-3", children: [_jsx("svg", { className: "w-5 h-5 text-orange-500 shrink-0 mt-0.5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" }) }), _jsxs("p", { className: "text-sm text-orange-800", children: ["This template requires the", " ", _jsx("strong", { children: template.tier === "pro"
                                                                    ? "₦40,000"
                                                                    : template.tier === "growth"
                                                                        ? "₦25,000"
                                                                        : "Free" }), " ", "plan. Your current plan doesn't support these advanced workflows."] })] }), _jsx(Link, { href: "/pricing", className: "block", children: _jsx(Button, { className: "w-full py-6 text-lg font-bold bg-gray-900 hover:bg-black text-white rounded-xl shadow-lg transition-all", children: "View Plans & Upgrade" }) })] })), _jsxs("p", { className: "text-center text-xs text-gray-400 mt-4 italic", children: ["estimated setup time: ", template.setupTime] })] })] })] }) }) }));
};
