"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Link from "next/link";
import { User, ChevronRight } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
export function ConversationList({ conversations }) {
    if (conversations.length === 0) {
        return (_jsxs("div", { className: "p-16 text-center flex flex-col items-center justify-center h-full", children: [_jsxs("div", { className: "h-12 w-12 bg-slate-100 text-slate-500 rounded-lg flex items-center justify-center mb-4", children: [_jsx(User, { className: "h-6 w-6" }), " "] }), _jsx("h3", { className: "text-lg font-medium text-slate-900 mb-1", children: "Inbox Empty" }), _jsx("p", { className: "text-slate-500 max-w-sm", children: "No customer messages or support requests yet." })] }));
    }
    return (_jsx("div", { className: "divide-y divide-slate-100", children: conversations.map((conv) => (_jsxs("div", { className: `relative p-4 hover:bg-slate-50 transition-colors cursor-pointer group flex items-start justify-between gap-4 ${conv.unread ? 'bg-indigo-50/50' : ''}`, children: [_jsx(Link, { href: `/dashboard/support/messages/${conv.id}`, className: "absolute inset-0" }), _jsxs("div", { className: "flex items-start gap-4", children: [_jsx("div", { className: "h-10 w-10 bg-slate-100 rounded-full flex items-center justify-center text-slate-500 shrink-0", children: _jsx(User, { className: "h-5 w-5" }) }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("span", { className: `font-semibold text-sm ${conv.unread ? 'text-slate-900' : 'text-slate-700'}`, children: conv.contactName }), conv.unread && (_jsx("span", { className: "h-2 w-2 rounded-full bg-indigo-600" })), _jsx("span", { className: "text-xs text-slate-400 font-normal", children: formatDistanceToNow(new Date(conv.lastMessageAt), { addSuffix: true }) })] }), _jsxs("p", { className: `text-sm line-clamp-1 ${conv.unread ? 'text-slate-800 font-medium' : 'text-slate-500'}`, children: [conv.direction === "OUTBOUND" && _jsx("span", { className: "text-slate-400 mr-1", children: "You:" }), conv.lastMessage] })] })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("span", { className: `px-2 py-1 rounded text-xs font-medium border ${conv.status === 'OPEN' ? 'bg-indigo-50 text-indigo-700 border-indigo-100' :
                                conv.status === 'RESOLVED' ? 'bg-slate-100 text-slate-600 border-slate-200' :
                                    'bg-slate-50 text-slate-500 border-slate-200'}`, children: conv.status }), _jsx(ChevronRight, { className: "h-4 w-4 text-slate-300 group-hover:text-slate-500 transition-colors" })] })] }, conv.id))) }));
}
