import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { prisma } from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import Link from "next/link";
import { Package, Clock, HelpCircle } from "lucide-react";
import { redirect } from "next/navigation";
export default async function OrdersPage({ searchParams }) {
    const session = await getServerSession(authOptions);
    if (!session?.user)
        return redirect("/api/auth/signin");
    const tab = searchParams.tab || "orders";
    const orders = tab === "orders" ? await prisma.order.findMany({
        where: { customerId: session.user.id },
        orderBy: { createdAt: "desc" },
        include: {
            _count: { select: { items: true } }
        }
    }) : [];
    const requests = tab === "requests" ? await prisma.sourcingRequest.findMany({
        where: { userId: session.user.id },
        orderBy: { createdAt: "desc" }
    }) : [];
    return (_jsxs("div", { className: "container mx-auto px-4 py-8 max-w-4xl", children: [_jsx("h1", { className: "text-2xl font-bold mb-6", children: "Activity" }), _jsxs("div", { className: "flex gap-4 border-b mb-6", children: [_jsx(Link, { href: "/orders?tab=orders", className: `pb-2 px-1 text-sm font-medium border-b-2 transition-colors ${tab === "orders" ? "border-black text-black" : "border-transparent text-gray-500 hover:text-black"}`, children: "My Orders" }), _jsx(Link, { href: "/orders?tab=requests", className: `pb-2 px-1 text-sm font-medium border-b-2 transition-colors ${tab === "requests" ? "border-black text-black" : "border-transparent text-gray-500 hover:text-black"}`, children: "Sourcing Requests" })] }), tab === "orders" && (_jsx(_Fragment, { children: orders.length === 0 ? (_jsxs("div", { className: "text-center py-20 bg-gray-50 rounded-xl border", children: [_jsx(Package, { className: "mx-auto h-12 w-12 text-gray-300 mb-4" }), _jsx("h3", { className: "text-lg font-medium", children: "No orders yet" }), _jsx("p", { className: "text-muted-foreground mb-6", children: "Start shopping to see your orders here." }), _jsx(Link, { href: "/", className: "text-primary hover:underline font-medium", children: "Browse Marketplace" })] })) : (_jsx("div", { className: "space-y-4", children: orders.map((order) => (_jsx(Link, { href: `/orders/${order.id}`, className: "block bg-white border rounded-lg p-4 hover:border-black transition-colors hover:shadow-sm", children: _jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("span", { className: "font-semibold", children: order.orderNumber }), _jsx("span", { className: `text-[10px] px-2 py-0.5 rounded-full font-bold uppercase ${order.status === 'DELIVERED' ? 'bg-green-100 text-green-700' :
                                                        order.status === 'CANCELLED' ? 'bg-red-100 text-red-700' :
                                                            'bg-gray-100 text-gray-700'}`, children: order.status })] }), _jsxs("div", { className: "text-sm text-muted-foreground flex items-center gap-4", children: [_jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Clock, { className: "h-3 w-3" }), new Date(order.createdAt).toLocaleDateString()] }), _jsx("span", { children: "\u2022" }), _jsxs("span", { children: [order._count.items, " items"] })] })] }), _jsxs("div", { className: "text-right", children: [_jsxs("div", { className: "font-bold", children: ["\u20A6", Number(order.total).toLocaleString()] }), _jsx("div", { className: "text-xs text-muted-foreground", children: "View details" })] })] }) }, order.id))) })) })), tab === "requests" && (_jsx(_Fragment, { children: requests.length === 0 ? (_jsxs("div", { className: "text-center py-20 bg-gray-50 rounded-xl border", children: [_jsx(HelpCircle, { className: "mx-auto h-12 w-12 text-gray-300 mb-4" }), _jsx("h3", { className: "text-lg font-medium", children: "No requests yet" }), _jsx("p", { className: "text-muted-foreground mb-6", children: "Need something from China? Submit a request." }), _jsx(Link, { href: "/sourcing/request", className: "inline-flex items-center justify-center h-10 px-6 rounded-lg bg-black text-white text-sm font-medium hover:bg-gray-800 transition-colors", children: "Create Request" })] })) : (_jsxs("div", { className: "space-y-4", children: [requests.map((request) => (_jsxs("div", { className: "bg-white border rounded-lg p-4 transition-colors", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("span", { className: "font-semibold", children: request.productName }), _jsx("span", { className: `text-[10px] px-2 py-0.5 rounded-full font-bold uppercase ${request.status === 'PENDING' ? 'bg-yellow-100 text-yellow-700' :
                                                                request.status === 'QUOTED' ? 'bg-green-100 text-green-700' :
                                                                    request.status === 'REJECTED' ? 'bg-red-100 text-red-700' :
                                                                        'bg-blue-100 text-blue-700'}`, children: request.status })] }), _jsx("p", { className: "text-sm text-muted-foreground line-clamp-2 mb-2", children: request.description }), _jsxs("div", { className: "text-xs text-muted-foreground flex items-center gap-4", children: [_jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Clock, { className: "h-3 w-3" }), new Date(request.createdAt).toLocaleDateString()] }), _jsx("span", { children: "\u2022" }), _jsxs("span", { children: ["Qty: ", request.quantity] })] })] }), request.status === 'QUOTED' && (_jsx(Link, { href: `/sourcing/request/${request.id}`, className: "text-sm font-bold text-blue-600 hover:underline", children: "View Quote" }))] }), request.adminNote && (_jsxs("div", { className: "mt-3 p-3 bg-gray-50 rounded text-sm text-gray-600 italic", children: ["\"", request.adminNote, "\""] }))] }, request.id))), _jsx("div", { className: "pt-6 border-t mt-8 text-center", children: _jsx(Link, { href: "/sourcing/request", className: "text-sm font-medium text-primary hover:underline", children: "+ Submit another request" }) })] })) }))] }));
}
