import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@vayva/ui";
export const CosmeticsBeautyTemplate = ({ businessName, demoMode, }) => {
    return (_jsxs("div", { className: "font-serif min-h-screen bg-[#FFF0F5] text-[#4A4A4A]", children: [_jsxs("header", { className: "py-6 px-4 text-center sticky top-0 bg-[#FFF0F5]/80 backdrop-blur z-50", children: [_jsx("div", { className: "font-bold text-2xl tracking-widest uppercase text-[#D88CA3]", children: businessName || "Glow by Ada" }), _jsxs("nav", { className: "flex justify-center gap-6 mt-3 text-xs font-bold uppercase tracking-wider text-[#9E6B7A]", children: [_jsx("span", { children: "Skin" }), _jsx("span", { children: "Hair" }), _jsx("span", { children: "Body" }), _jsx("span", { children: "Kits" })] })] }), _jsx("section", { className: "px-4 mb-10", children: _jsxs("div", { className: "aspect-[4/5] rounded-[2rem] overflow-hidden relative shadow-xl shadow-[#D88CA3]/20", children: [_jsx("img", { src: "https://images.unsplash.com/photo-1596462502278-27bfdd403348?w=800&q=80", alt: "Glow", className: "w-full h-full object-cover" }), _jsxs("div", { className: "absolute inset-0 bg-gradient-to-t from-[#4A0E1F]/60 to-transparent flex flex-col justify-end p-8 text-white", children: [_jsx("h2", { className: "text-3xl font-light italic mb-2", children: "Radiance Kit" }), _jsx("p", { className: "text-sm opacity-90 mb-6 font-sans", children: "Restore your natural barrier with our 3-step routine." }), _jsx(Button, { className: "bg-white text-[#4A0E1F] w-max px-6 py-3 rounded-full font-bold text-xs uppercase tracking-widest hover:bg-[#FFE4E1] h-auto", children: "Shop Routine" })] })] }) }), _jsxs("section", { className: "pl-4 pb-10 overflow-x-hidden", children: [_jsxs("div", { className: "flex justify-between items-end pr-4 mb-4", children: [_jsx("h3", { className: "font-bold text-lg text-[#8B4C5F]", children: "Top Rated" }), _jsx("a", { href: "#", className: "text-xs border-b border-[#D88CA3] pb-0.5", children: "View All" })] }), _jsx("div", { className: "flex gap-4 overflow-x-auto pb-4 pr-4", children: [
                            {
                                name: "Vitamin C Serum",
                                price: "₦12,500",
                                reviews: "4.9",
                                img: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80",
                            },
                            {
                                name: "Hydrating Cleanser",
                                price: "₦8,000",
                                reviews: "4.8",
                                img: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&q=80",
                            },
                            {
                                name: "Rose Water Toner",
                                price: "₦6,500",
                                reviews: "5.0",
                                img: "https://images.unsplash.com/photo-1608248597279-f99d160bfbc8?w=400&q=80",
                            },
                        ].map((item, i) => (_jsxs("div", { className: "min-w-[160px] group", children: [_jsxs("div", { className: "aspect-[3/4] bg-white rounded-2xl overflow-hidden mb-3 p-4 relative shadow-sm", children: [_jsx("img", { src: item.img, className: "w-full h-full object-contain group-hover:scale-110 transition-transform duration-500", alt: item.name }), _jsxs("div", { className: "absolute top-2 right-2 bg-[#FFF0F5] text-[#D88CA3] text-[10px] font-bold px-2 py-1 rounded-full flex items-center gap-1", children: ["\u2605 ", item.reviews] })] }), _jsx("h4", { className: "font-bold text-sm text-[#4A4A4A] mb-1", children: item.name }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-xs font-bold text-[#D88CA3] bg-white px-2 py-1 rounded-md", children: item.price }), _jsx(Button, { className: "w-6 h-6 bg-[#4A0E1F] text-white rounded-full flex items-center justify-center text-xs h-auto p-0 min-w-[1.5rem]", children: "+" })] })] }, i))) })] }), _jsxs("div", { className: "mx-4 bg-white rounded-2xl p-6 flex items-center gap-4 shadow-sm border border-[#FFE4E1]", children: [_jsx("div", { className: "w-12 h-12 rounded-full bg-[#FFE4E1] flex items-center justify-center text-xl", children: "\uD83D\uDC69\uD83C\uDFFD\u200D\u2695\uFE0F" }), _jsxs("div", { className: "flex-1", children: [_jsx("h4", { className: "font-bold text-sm text-[#8B4C5F] mb-1", children: "Confused about your skin?" }), _jsx("p", { className: "text-[10px] text-gray-500 mb-2", children: "Chat with our aesthetician for a personalized routine." })] }), _jsx(Button, { className: "bg-[#D88CA3] text-white px-4 py-2 rounded-full text-[10px] font-bold uppercase hover:bg-[#C06C84] h-auto", children: "Chat" })] })] }));
};
