"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Image from "next/image";
import { Zap, ShieldCheck } from "lucide-react";
import * as motion from "framer-motion/client";
export default function TrustVisualSection() {
    return (_jsx("section", { className: "pb-24 px-4", children: _jsx(motion.div, { initial: { opacity: 0, y: 40 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.8 }, className: "max-w-6xl mx-auto", children: _jsxs("div", { className: "relative group", children: [_jsx("div", { className: "absolute -inset-1 bg-gradient-to-r from-green-400 to-blue-500 rounded-[32px] blur opacity-20 group-hover:opacity-30 transition duration-1000" }), _jsxs("div", { className: "relative bg-white border border-gray-200 rounded-[32px] shadow-2xl overflow-hidden", children: [_jsx("div", { className: "absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-[#22C55E] to-blue-500" }), _jsxs("div", { className: "p-4 bg-gray-50 border-b border-gray-100 flex items-center gap-2", children: [_jsxs("div", { className: "flex gap-1.5 ml-2", children: [_jsx("div", { className: "w-3 h-3 rounded-full bg-red-400" }), _jsx("div", { className: "w-3 h-3 rounded-full bg-yellow-400" }), _jsx("div", { className: "w-3 h-3 rounded-full bg-green-400" })] }), _jsx("div", { className: "mx-auto bg-white px-4 py-1 rounded-full text-[10px] font-bold text-gray-400 uppercase tracking-widest border border-gray-200", children: "Yourstore.vayva.ng" })] }), _jsx("div", { className: "p-8 lg:p-12", children: _jsxs("div", { className: "grid lg:grid-cols-[1fr_0.65fr] gap-12 items-center", children: [_jsxs("div", { children: [_jsx("div", { className: "inline-flex items-center gap-2 px-3 py-1 rounded-full bg-green-50 text-[#22C55E] text-xs font-bold uppercase mb-6", children: "The Vayva Engine" }), _jsxs("h2", { className: "text-4xl font-bold text-[#0F172A] mb-8 leading-tight", children: ["How your business", _jsx("br", {}), "stays in sync."] }), _jsx("div", { className: "space-y-10", children: [
                                                        {
                                                            num: 1,
                                                            title: "Chat natively",
                                                            text: "Customers message you on WhatsApp. No new apps for them.",
                                                        },
                                                        {
                                                            num: 2,
                                                            title: "Process with AI",
                                                            text: "Vayva assists by parsing conversations and extracting order details.",
                                                        },
                                                        {
                                                            num: 3,
                                                            title: "Record eternally",
                                                            text: "Orders, payments, and delivery statuses are logged in clean records.",
                                                        },
                                                    ].map((step) => (_jsxs("div", { className: "flex items-start gap-6 group", children: [_jsx("div", { className: "flex-shrink-0 w-10 h-10 bg-white border-2 border-green-100 text-[#22C55E] rounded-full flex items-center justify-center text-sm font-bold group-hover:bg-[#22C55E] group-hover:text-white transition-all shadow-sm", children: step.num }), _jsxs("div", { className: "pt-1", children: [_jsx("p", { className: "text-lg font-bold text-[#0F172A] mb-1", children: step.title }), _jsx("p", { className: "text-[#64748B] text-sm leading-relaxed", children: step.text })] })] }, step.num))) })] }), _jsxs("div", { className: "relative", children: [_jsxs("div", { className: "relative rounded-[32px] overflow-hidden shadow-2xl border border-gray-100 group-hover:scale-[1.02] transition-transform duration-700", children: [_jsx(Image, { src: "/images/calm-solution.jpg", alt: "Relaxed merchant managing business on tablet", width: 800, height: 600, className: "w-full h-auto object-cover" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/60 to-transparent flex items-end p-8", children: _jsx("div", { className: "bg-white/90 backdrop-blur-md p-4 rounded-xl border border-white/20 shadow-lg", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-green-500 flex items-center justify-center", children: _jsx(Zap, { className: "w-6 h-6 text-white" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-[10px] uppercase font-black text-gray-500", children: "System Status" }), _jsx("p", { className: "text-sm font-bold text-gray-900", children: "All Systems Running" })] })] }) }) })] }), _jsx("div", { className: "absolute -bottom-6 -right-6 bg-white p-4 rounded-2xl shadow-2xl border border-gray-100", children: _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-blue-500 flex items-center justify-center", children: _jsx(ShieldCheck, { className: "w-6 h-6 text-white" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-[10px] uppercase font-black text-gray-400", children: "Peace of Mind" }), _jsx("p", { className: "text-sm font-bold text-gray-900", children: "100% Audit Ready" })] })] }) })] })] }) })] })] }) }) }));
}
