"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Link from "next/link";
import { useRouter } from "next/navigation"; // Import useRouter
import { Search, MapPin, ShoppingBag } from "lucide-react";
import { Button } from "@vayva/ui";
export default function MarketplaceHome() {
    const router = useRouter(); // Initialize useRouter
    return (_jsxs("div", { className: "min-h-screen bg-gray-50 pb-20", children: [_jsxs("header", { className: "sticky top-0 z-50 bg-white border-b border-gray-100 px-4 py-3 flex items-center justify-between shadow-sm", children: [_jsx("div", { className: "flex items-center gap-2 font-bold text-xl tracking-tight text-[#22C55E]", children: "Vayva" }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Button, { variant: "ghost", size: "icon", className: "rounded-full text-gray-600", "aria-label": "Search", title: "Search", onClick: () => router.push("/search"), children: _jsx(Search, { size: 20 }) }), _jsx(Button, { variant: "ghost", size: "icon", className: "rounded-full text-gray-600", "aria-label": "Cart", title: "Cart", children: _jsx(ShoppingBag, { size: 20 }) })] })] }), _jsxs("div", { className: "bg-white px-4 py-3 border-b border-gray-100 flex items-center gap-2 text-sm text-gray-600", children: [_jsx(MapPin, { size: 14, className: "text-[#22C55E]" }), _jsx("span", { children: "Lagos, Nigeria" }), " \u2022 ", _jsx("span", { className: "text-[#22C55E] font-medium", children: "Change" })] }), _jsxs("main", { className: "max-w-7xl mx-auto px-4 py-6 space-y-8", children: [_jsxs("section", { children: [_jsx("h2", { className: "font-bold text-lg mb-4 text-gray-900", children: "Browse Categories" }), _jsx("div", { className: "grid grid-cols-4 gap-4 text-center", children: ["Vehicles", "Property", "Phones", "Fashion", "Home", "Food", "Jobs", "More"].map((cat) => (_jsxs(Button, { onClick: () => router.push(`/search?category=${encodeURIComponent(cat === "More" ? "All" : cat)}`), variant: "ghost", className: "flex flex-col items-center gap-2 h-auto p-0", children: [_jsx("div", { className: "w-14 h-14 bg-white rounded-2xl shadow-sm border border-gray-100 flex items-center justify-center text-xs font-bold text-gray-400 hover:border-[#22C55E] hover:text-[#22C55E] transition-colors", children: cat[0] }), _jsx("span", { className: "text-xs font-medium text-gray-700", children: cat })] }, cat))) })] }), _jsxs("section", { children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("h2", { className: "font-bold text-lg text-gray-900", children: "Trending Near You" }), _jsx(Link, { href: "/search", className: "text-sm text-[#22C55E] font-medium", children: "See All" })] }), _jsx("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-4", children: [1, 2, 3, 4].map((i) => (_jsxs("div", { className: "bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden", children: [_jsx("div", { className: "aspect-square bg-gray-100 relative" }), _jsxs("div", { className: "p-3", children: [_jsx("h3", { className: "font-medium text-gray-900 truncate", children: "iPhone 14 Pro Max" }), _jsx("p", { className: "text-[#22C55E] font-bold mt-1", children: "\u20A6950,000" }), _jsx("p", { className: "text-xs text-gray-500 mt-1", children: "Lekki Phase 1" })] })] }, i))) })] })] })] }));
}
