"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Button, Icon } from "@vayva/ui";
const NAV_ITEMS = [
    { name: "Merchants", path: "/ops/merchants", icon: "Store" },
    { name: "Moderation", path: "/ops/moderation", icon: "Gavel" },
    { name: "Disputes", path: "/ops/disputes", icon: "AlertTriangle" },
    { name: "Payouts", path: "/ops/payouts", icon: "CreditCard" },
    { name: "Compliance", path: "/ops/compliance", icon: "Shield" },
    { name: "Support", path: "/ops/support", icon: "Headphones" },
];
export function OpsShell({ children, title, description, actions, }) {
    const pathname = usePathname();
    return (_jsxs("div", { className: "min-h-screen bg-[#142210] flex text-white font-sans selection:bg-red-500/30", children: [_jsxs("aside", { className: "w-[300px] border-r border-white/5 flex flex-col fixed inset-y-0 bg-[#0b141a]/95 backdrop-blur-xl z-50", children: [_jsxs("div", { className: "h-[72px] flex items-center px-6 border-b border-white/5 gap-3", children: [_jsx("div", { className: "w-8 h-8 rounded bg-red-500/20 text-red-500 flex items-center justify-center font-bold border border-red-500/30", children: "O" }), _jsx("span", { className: "font-bold text-lg tracking-tight", children: "Vayva Ops" }), _jsx("span", { className: "ml-auto px-2 py-0.5 rounded bg-red-500 text-white text-[10px] font-bold uppercase tracking-wider", children: "Prod" })] }), _jsx("nav", { className: "flex-1 p-4 space-y-1 overflow-y-auto", children: NAV_ITEMS.map((item) => {
                            const isActive = pathname.startsWith(item.path);
                            return (_jsx(Link, { href: item.path, children: _jsxs("div", { className: `flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium transition-colors
                                    ${isActive ? "bg-white/10 text-white" : "text-text-secondary hover:text-white hover:bg-white/5"}
                                `, children: [_jsx(Icon, { name: item.icon, size: 20, className: isActive ? "text-white" : "text-text-secondary" }), item.name] }) }, item.path));
                        }) }), _jsx("div", { className: "p-4 border-t border-white/5", children: _jsxs("div", { className: "flex items-center gap-3 px-4 py-3", children: [_jsx("div", { className: "w-8 h-8 rounded-full bg-white/10 flex items-center justify-center text-xs font-bold", children: "JD" }), _jsxs("div", { className: "flex-1 overflow-hidden", children: [_jsx("div", { className: "text-sm font-bold truncate", children: "John Doe" }), _jsx("div", { className: "text-xs text-text-secondary truncate", children: "Senior Risk Analyst" })] }), _jsx(Icon, { name: "LogOut", size: 18, className: "text-text-secondary hover:text-white cursor-pointer" })] }) })] }), _jsxs("main", { className: "flex-1 ml-[300px] min-h-screen flex flex-col", children: [_jsxs("header", { className: "h-[72px] border-b border-white/5 bg-[#142210]/90 backdrop-blur sticky top-0 z-40 px-8 flex items-center justify-between gap-8", children: [_jsxs("div", { className: "flex-1 max-w-2xl relative", children: [_jsx(Icon, { name: "Search", className: "absolute left-3 top-1/2 -translate-y-1/2 text-text-secondary", size: 18 }), _jsx("input", { className: "w-full bg-white/5 border border-white/10 rounded-full pl-10 pr-4 py-2 text-sm text-white focus:outline-none focus:border-white/20 placeholder:text-text-secondary transition-all", placeholder: "Search merchant, order ID, transaction reference..." }), _jsxs("div", { className: "absolute right-2 top-1.5 flex gap-1", children: [_jsx("kbd", { className: "px-1.5 py-0.5 rounded bg-white/5 border border-white/10 text-[10px] font-mono text-text-secondary", children: "\u2318" }), _jsx("kbd", { className: "px-1.5 py-0.5 rounded bg-white/5 border border-white/10 text-[10px] font-mono text-text-secondary", children: "K" })] })] }), _jsx("div", { className: "flex items-center gap-4", children: _jsxs(Button, { variant: "ghost", size: "icon", className: "text-text-secondary hover:text-white relative", children: [_jsx(Icon, { name: "Bell" }), _jsx("span", { className: "absolute top-2 right-2 w-2 h-2 bg-red-500 rounded-full" })] }) })] }), _jsxs("div", { className: "p-8 max-w-[1400px] w-full mx-auto", children: [(title || description || actions) && (_jsxs("div", { className: "flex justify-between items-start mb-8", children: [_jsxs("div", { children: [title && (_jsx("h1", { className: "text-2xl font-bold text-white mb-1", children: title })), description && (_jsx("p", { className: "text-text-secondary", children: description }))] }), actions && _jsx("div", { className: "flex gap-3", children: actions })] })), children] })] })] }));
}
