"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useRouter } from "next/navigation";
import { Button, Icon, cn } from "@vayva/ui";
import { TimeDisplay } from "@/components/shared/TimeDisplay";
// --- Sidebar List ---
export const InboxSidebar = ({ threads, activeId, }) => {
    const router = useRouter();
    return (_jsxs("div", { className: "w-80 border-r border-gray-100 bg-white flex flex-col h-full overflow-hidden", children: [_jsxs("div", { className: "p-4 border-b border-gray-100 flex items-center justify-between", children: [_jsx("h2", { className: "font-bold text-black", children: "Inbox" }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Button, { className: "text-gray-400 hover:text-black", children: _jsx(Icon, { name: "Filter", size: 16 }) }), _jsx(Button, { className: "text-gray-400 hover:text-black", children: _jsx(Icon, { name: "Search", size: 16 }) })] })] }), _jsx("div", { className: "flex-1 overflow-y-auto", children: threads.map((thread) => (_jsxs("div", { onClick: () => router.push(`/admin/wa-agent/inbox/${thread.id}`), className: cn("p-4 border-b border-gray-50 cursor-pointer hover:bg-gray-50 transition-colors group", activeId === thread.id
                        ? "bg-blue-50/50 border-l-4 border-l-blue-600 pl-[13px]"
                        : "pl-4"), children: [_jsxs("div", { className: "flex justify-between items-start mb-1", children: [_jsx("span", { className: cn("font-bold text-sm", activeId === thread.id ? "text-blue-900" : "text-black"), children: thread.customerName }), _jsx("span", { className: "text-[10px] text-gray-400", children: _jsx(TimeDisplay, { date: thread.lastMessageTime, format: "time" }) })] }), _jsx("p", { className: "text-xs text-gray-500 line-clamp-1 group-hover:text-gray-700", children: thread.lastMessage }), _jsxs("div", { className: "mt-2 flex gap-2", children: [thread.status === "waiting" && (_jsx("span", { className: "bg-yellow-100 text-yellow-700 text-[10px] font-bold px-1.5 py-0.5 rounded", children: "WAITING" })), thread.status === "open" && (_jsx("span", { className: "bg-green-100 text-green-700 text-[10px] font-bold px-1.5 py-0.5 rounded", children: "OPEN" }))] })] }, thread.id))) })] }));
};
// --- Chat Window ---
export const ChatWindow = ({ thread }) => {
    if (!thread) {
        return (_jsxs("div", { className: "flex-1 flex flex-col items-center justify-center bg-gray-50/50 text-gray-400 p-8 text-center", children: [_jsx("div", { className: "w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mb-4", children: _jsx(Icon, { name: "MessageSquare", size: 24 }) }), _jsx("p", { children: "Select a conversation to start chatting." })] }));
    }
    return (_jsxs("div", { className: "flex-1 flex flex-col bg-[#E5DDD5]/10 h-full overflow-hidden relative", children: [_jsxs("div", { className: "h-16 border-b border-gray-200 bg-white flex items-center justify-between px-6 shrink-0 z-10", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold", children: thread.customerName.charAt(0) }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-black text-sm", children: thread.customerName }), _jsx("p", { className: "text-xs text-gray-500", children: thread.customerPhone })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsxs(Button, { onClick: () => alert("Conversation reported for compliance review."), className: "p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-full transition-colors flex items-center gap-2 text-xs font-medium", title: "Report Conversation", children: [_jsx(Icon, { name: "ShieldAlert", size: 16 }), _jsx("span", { className: "hidden md:inline", children: "Report" })] }), _jsx(Button, { variant: "outline", size: "sm", children: "Resolve" })] })] }), _jsx("div", { className: "flex-1 p-6 overflow-y-auto flex flex-col gap-4 bg-[url('https://user-images.githubusercontent.com/15075759/28719144-86dc0f70-73b1-11e7-911d-60d70fcded21.png')] bg-repeat bg-opacity-5", children: (thread.messages.length > 0
                    ? thread.messages
                    : [
                        {
                            id: "test1",
                            text: thread.lastMessage,
                            sender: "user",
                            timestamp: thread.lastMessageTime,
                        },
                    ]).map((msg) => (_jsxs("div", { className: cn("max-w-[70%] p-3 rounded-xl text-sm shadow-sm relative", msg.sender === "user"
                        ? "bg-white self-start rounded-tl-none"
                        : "bg-[#d9fdd3] self-end rounded-tr-none"), children: [_jsx("p", { className: "text-black", children: msg.text }), _jsx("span", { className: "text-[10px] text-gray-400 block text-right mt-1 opacity-70 border-t border-black/5 pt-1", children: _jsx(TimeDisplay, { date: msg.timestamp, format: "time" }) })] }, msg.id))) }), _jsx("div", { className: "p-4 bg-white border-t border-gray-200 shrink-0", children: _jsxs("div", { className: "flex gap-2", children: [_jsx("input", { type: "text", placeholder: "Type a message...", className: "flex-1 h-10 border border-gray-200 rounded-full px-4 text-sm focus:outline-none focus:border-blue-500" }), _jsx(Button, { className: "w-10 h-10 rounded-full bg-[#00A884] text-white flex items-center justify-center hover:bg-[#008f6f] transition-colors", children: _jsx(Icon, { name: "Send", size: 18 }) })] }) })] }));
};
// --- AI Actions Panel ---
export const AiActionsPanel = ({ thread }) => {
    if (!thread)
        return null;
    return (_jsxs("div", { className: "w-80 border-l border-gray-100 bg-white flex flex-col h-full overflow-y-auto p-4 gap-6", children: [_jsx("h3", { className: "font-bold text-black text-sm uppercase tracking-wide", children: "AI Assistant" }), thread.aiSuggestions?.reply && (_jsxs("div", { className: "bg-purple-50 p-4 rounded-xl border border-purple-100", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2 text-purple-700", children: [_jsx(Icon, { name: "Zap", size: 14 }), _jsx("span", { className: "text-xs font-bold", children: "Suggested Reply" })] }), _jsx("p", { className: "text-sm text-black mb-3", children: thread.aiSuggestions.reply }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Button, { size: "sm", className: "w-full bg-purple-600 hover:bg-purple-700 text-white", children: "Use" }), _jsx(Button, { size: "sm", variant: "outline", className: "w-10", children: _jsx(Icon, { name: "Pencil", size: 14 }) })] })] })), thread.aiSuggestions?.action && (_jsxs("div", { className: "bg-orange-50 p-4 rounded-xl border border-orange-100", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2 text-orange-700", children: [_jsx(Icon, { name: "ShieldAlert", size: 14 }), _jsx("span", { className: "text-xs font-bold", children: "Approval Required" })] }), _jsx("p", { className: "text-sm font-bold text-black", children: thread.aiSuggestions.action.description }), _jsxs("p", { className: "text-xs text-gray-500 mt-1 mb-3", children: ["Risk Level:", " ", _jsx("span", { className: "uppercase font-bold text-orange-600", children: thread.aiSuggestions.action.risk })] }), _jsxs("div", { className: "grid grid-cols-2 gap-2", children: [_jsx(Button, { size: "sm", variant: "outline", className: "text-red-600 border-red-200 hover:bg-red-50", children: "Reject" }), _jsx(Button, { size: "sm", className: "bg-orange-600 hover:bg-orange-700 text-white", children: "Approve" })] })] })), _jsxs("div", { children: [_jsx("h4", { className: "text-xs font-bold text-gray-400 mb-2 uppercase", children: "Quick Share" }), _jsx("div", { className: "flex flex-col gap-2", children: _jsxs(Button, { className: "flex items-center gap-3 p-2 hover:bg-gray-50 rounded-lg text-left transition-colors", children: [_jsx("div", { className: "w-10 h-10 bg-gray-100 rounded overflow-hidden" }), _jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "text-xs font-bold text-black", children: "Vintage Jacket" }), _jsx("p", { className: "text-[10px] text-gray-500", children: "\u20A6 15,000" })] }), _jsx(Icon, { name: "Plus", size: 14, className: "text-gray-400" })] }) })] })] }));
};
