import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Search, Filter, CreditCard, RefreshCw, Calendar } from "lucide-react";
import { Button } from "@vayva/ui";
export const FilterBar = ({ onFilterChange, onSearch, onRefresh, }) => {
    const [status, setStatus] = useState("ALL");
    const [search, setSearch] = useState("");
    return (_jsxs("div", { className: "flex flex-col md:flex-row gap-4 mb-8 p-1", children: [_jsxs("div", { className: "flex-1 relative group", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 group-focus-within:text-black transition-colors", size: 18 }), _jsx("input", { type: "text", placeholder: "Search by order ID, customer or ref...", className: "w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-xl focus:ring-4 focus:ring-vayva-green/10 focus:border-vayva-green transition-all font-medium text-sm placeholder:text-gray-400", value: search, onChange: (e) => {
                            setSearch(e.target.value);
                            onSearch(e.target.value);
                        } })] }), _jsxs("div", { className: "flex gap-2 text-sm", children: [_jsxs("div", { className: "relative", children: [_jsx(Filter, { className: "absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none", size: 14 }), _jsxs("select", { "aria-label": "Filter by Status", className: "pl-9 pr-8 py-2.5 border border-gray-200 rounded-xl bg-white focus:ring-4 focus:ring-vayva-green/10 focus:border-vayva-green appearance-none font-bold text-gray-700 cursor-pointer min-w-[120px]", value: status, onChange: (e) => {
                                    setStatus(e.target.value);
                                    onFilterChange({ status: e.target.value });
                                }, children: [_jsx("option", { value: "ALL", children: "Status" }), _jsx("option", { value: "NEW", children: "New" }), _jsx("option", { value: "PROCESSING", children: "Processing" }), _jsx("option", { value: "READY", children: "Ready" }), _jsx("option", { value: "COMPLETED", children: "Completed" })] })] }), _jsxs("div", { className: "relative", children: [_jsx(Calendar, { className: "absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none", size: 14 }), _jsxs("select", { "aria-label": "Filter by Time", className: "pl-9 pr-8 py-2.5 border border-gray-200 rounded-xl bg-white focus:ring-4 focus:ring-vayva-green/10 focus:border-vayva-green appearance-none font-bold text-gray-700 cursor-pointer min-w-[120px]", children: [_jsx("option", { value: "ALL", children: "Any Time" }), _jsx("option", { value: "today", children: "Today" }), _jsx("option", { value: "7d", children: "7 Days" }), _jsx("option", { value: "30d", children: "30 Days" })] })] }), _jsxs("div", { className: "relative", children: [_jsx(CreditCard, { className: "absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none", size: 14 }), _jsxs("select", { "aria-label": "Filter by Payment", className: "pl-9 pr-8 py-2.5 border border-gray-200 rounded-xl bg-white focus:ring-4 focus:ring-vayva-green/10 focus:border-vayva-green appearance-none font-bold text-gray-700 cursor-pointer min-w-[120px]", onChange: (e) => onFilterChange({ paymentStatus: e.target.value }), children: [_jsx("option", { value: "ALL", children: "Payment" }), _jsx("option", { value: "PAID", children: "Paid" }), _jsx("option", { value: "PENDING", children: "Pending" })] })] }), _jsx(Button, { variant: "outline", size: "icon", onClick: onRefresh, className: "border-gray-200 hover:bg-gray-50 text-gray-500 w-11 h-11 rounded-xl shadow-sm transition-all active:scale-90", children: _jsx(RefreshCw, { size: 18 }) })] })] }));
};
