"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button, Icon } from "@vayva/ui";
// 1. Items Card
export const ItemsCard = ({ order }) => (_jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden p-6 flex flex-col gap-6", children: [_jsx("h3", { className: "font-bold text-black", children: "Order Items" }), _jsx("div", { className: "flex flex-col gap-4", children: order.items.map((item) => (_jsxs("div", { className: "flex gap-4 border-b border-gray-50 pb-4 last:border-0 last:pb-0", children: [_jsx("div", { className: "w-16 h-16 bg-gray-100 rounded-lg shrink-0 overflow-hidden", children: item.image && (_jsx("img", { src: item.image, className: "w-full h-full object-cover", alt: item.title })) }), _jsxs("div", { className: "flex-1 flex flex-col justify-center", children: [_jsx("h4", { className: "text-sm font-bold text-black", children: item.title }), item.variantId && (_jsxs("p", { className: "text-xs text-[#525252]", children: ["Variant: ", item.variantId.split("-").pop()] }))] }), _jsxs("div", { className: "text-right flex flex-col justify-center", children: [_jsxs("p", { className: "text-sm font-bold text-black", children: ["\u20A6 ", Number(item.price).toLocaleString()] }), _jsxs("p", { className: "text-xs text-[#525252]", children: ["x ", item.quantity] })] })] }, item.id))) }), _jsxs("div", { className: "bg-gray-50 -mx-6 -mb-6 p-6 flex flex-col gap-2 text-sm", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-[#525252]", children: "Subtotal" }), _jsxs("span", { className: "font-medium", children: ["\u20A6 ", Number(order.subtotal).toLocaleString()] })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-[#525252]", children: "Shipping" }), _jsxs("span", { className: "font-medium", children: ["\u20A6 ", Number(order.shippingTotal).toLocaleString()] })] }), _jsxs("div", { className: "flex justify-between font-black text-lg text-black pt-2 border-t border-gray-200 mt-2", children: [_jsx("span", { children: "Total" }), _jsxs("span", { children: ["\u20A6 ", Number(order.total).toLocaleString()] })] })] })] }));
// 2. Timeline Card
export const TimelineCard = ({ events }) => (_jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden p-6 flex flex-col gap-6", children: [_jsx("h3", { className: "font-bold text-black", children: "Timeline" }), _jsx("div", { className: "relative pl-4 border-l-2 border-gray-100 flex flex-col gap-8", children: events.map((evt, i) => (_jsxs("div", { className: "relative", children: [_jsx("div", { className: "absolute -left-[21px] top-1 w-3 h-3 rounded-full bg-black ring-4 ring-white" }), _jsx("h4", { className: "text-sm font-bold text-black", children: evt.text }), _jsx("span", { className: "text-[10px] text-gray-400 mt-1 block", children: new Date(evt.createdAt).toLocaleString() })] }, evt.id))) })] }));
// 3. Customer Card
export const CustomerCard = ({ customer }) => (_jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden p-6 flex flex-col gap-4", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("h3", { className: "font-bold text-black", children: "Customer" }), _jsx(Link, { href: `/dashboard/customers/${customer.id}`, className: "text-xs text-vayva-green font-bold hover:underline", children: "View Profile" })] }), _jsxs("div", { className: "flex flex-col gap-2 text-sm", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-8 h-8 rounded-full bg-studio-gray text-black flex items-center justify-center font-bold text-xs ring-1 ring-studio-border", children: customer.name.charAt(0) }), _jsxs("div", { children: [_jsx("p", { className: "font-bold text-black", children: customer.name }), _jsx("p", { className: "text-xs text-[#525252]", children: "1 Order" })] })] }), _jsxs("div", { className: "pt-2 border-t border-gray-50 flex flex-col gap-2", children: [_jsxs("a", { href: `mailto:${customer.email}`, className: "flex items-center gap-2 text-[#525252] hover:text-black", children: [_jsx(Icon, { name: "Mail", size: 14 }), " ", customer.email] }), _jsxs("a", { href: `tel:${customer.phone}`, className: "flex items-center gap-2 text-[#525252] hover:text-black", children: [_jsx(Icon, { name: "Phone", size: 14 }), " ", customer.phone] })] })] })] }));
// 4. Delivery Card
export const DeliveryCard = ({ order, onCreateTask, }) => (_jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden p-6 flex flex-col gap-4", children: [_jsx("h3", { className: "font-bold text-black", children: "Delivery" }), _jsxs("div", { className: "text-sm text-[#525252]", children: [_jsx("p", { className: "font-bold text-black mb-1", children: "Details" }), _jsxs("p", { children: ["Method:", " ", order.timeline?.[0]?.metadata?.deliveryMethod || "Not specified"] }), _jsxs("p", { children: ["Address: ", order.timeline?.[0]?.metadata?.address || "N/A"] })] }), order.deliveryTask ? (_jsxs("div", { className: "bg-gray-50 p-3 rounded-lg border border-gray-100", children: [_jsx("p", { className: "text-xs font-bold text-[#525252] mb-1", children: "Delivery Task Status" }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-yellow-400" }), _jsx("span", { className: "text-sm font-medium capitalize", children: order.deliveryTask.status.replace("_", " ") })] }), order.deliveryTask.trackingUrl && (_jsx("a", { href: order.deliveryTask.trackingUrl, target: "_blank", className: "text-xs text-blue-600 hover:underline mt-1 block", children: "Track Delivery" }))] })) : (_jsx(Button, { variant: "outline", className: "w-full justify-center", onClick: onCreateTask, children: "Create Delivery Task" }))] }));
import Link from "next/link";
