import { env } from "../env";

export const config = {
  NODE_ENV: env.NODE_ENV,
  PORT: env.PORT,
  DATABASE_URL: env.DATABASE_URL,
  JWT_SECRET: env.JWT_SECRET,
  COOKIE_SECRET: env.COOKIE_SECRET,
  NEXT_PUBLIC_APP_URL: env.NEXT_PUBLIC_APP_URL,
  services: {
    AUTH: env.SERVICE_URL_AUTH,
    ORDERS: env.SERVICE_URL_ORDERS,
    PAYMENTS: env.SERVICE_URL_PAYMENTS,
    CORE: env.SERVICE_URL_CORE,
    WHATSAPP: env.SERVICE_URL_WHATSAPP,
    AI: env.SERVICE_URL_AI,
    APPROVALS: env.SERVICE_URL_APPROVALS,
    NOTIFICATIONS: env.SERVICE_URL_NOTIFICATIONS,
    SUPPORT: env.SERVICE_URL_SUPPORT,
    MERCHANT_ADMIN: env.SERVICE_URL_MERCHANT_ADMIN,
    OPS_CONSOLE: env.SERVICE_URL_OPS_CONSOLE,
    STOREFRONT: env.SERVICE_URL_STOREFRONT,
  },
};

