import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Icon, cn } from "@vayva/ui";
export const DependencyMatrix = ({ blockingIssues }) => {
    if (blockingIssues.length === 0) {
        return (_jsxs("div", { className: "mt-8 bg-gradient-to-r from-green-50 to-emerald-50 rounded-2xl border border-green-100 p-6 flex flex-col md:flex-row md:items-center justify-between gap-4", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "w-12 h-12 rounded-full bg-green-100 text-green-600 flex items-center justify-center shrink-0", children: _jsx(Icon, { name: "Check", size: 24 }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-bold text-green-900", children: "All Systems Operational" }), _jsx("p", { className: "text-green-700 text-sm", children: "Your account is fully set up. No blocking issues detected." })] })] }), _jsx("div", { className: "text-green-800 text-xs font-mono bg-white/50 px-3 py-1 rounded-full border border-green-200", children: "STATUS: HEALTHY" })] }));
    }
    return (_jsxs("div", { className: "mt-8", children: [_jsxs("h3", { className: "text-sm font-bold text-gray-500 uppercase tracking-widest mb-4 flex items-center gap-2", children: [_jsx(Icon, { name: "Activity", size: 16 }), "Action Required"] }), _jsx("div", { className: "bg-white rounded-2xl border border-gray-200 divide-y divide-gray-100 overflow-hidden", children: blockingIssues.map((issue) => (_jsxs("div", { className: "p-4 flex flex-col md:flex-row md:items-center gap-4 group hover:bg-red-50/10 transition-colors", children: [_jsx("div", { className: cn("w-10 h-10 rounded-full flex items-center justify-center shrink-0", issue.severity === "critical"
                                ? "bg-red-100 text-red-600"
                                : "bg-amber-100 text-amber-600"), children: _jsx(Icon, { name: issue.severity === "critical" ? "CircleX" : "Info", size: 20 }) }), _jsxs("div", { className: "flex-1", children: [_jsx("h4", { className: "font-bold text-gray-900", children: issue.title }), _jsx("p", { className: "text-sm text-gray-500", children: issue.description })] }), _jsxs("a", { href: issue.actionUrl, className: "text-sm font-bold text-blue-600 hover:text-blue-700 hover:underline flex items-center gap-1 whitespace-nowrap", children: ["Fix Issue ", _jsx(Icon, { name: "ArrowRight", size: 14 })] })] }, issue.id))) })] }));
};
