import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CheckCircle, AlertCircle, XCircle, Info } from "lucide-react";
export function ComplianceReport({ report }) {
    const { checks, details, isValid } = report;
    return (_jsxs("div", { className: "bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm", children: [_jsxs("div", { className: `p-4 flex items-center justify-between border-b ${isValid ? "bg-green-50" : "bg-red-50"}`, children: [_jsxs("div", { className: "flex items-center gap-2", children: [isValid ? (_jsx(CheckCircle, { className: "text-green-600", size: 20 })) : (_jsx(AlertCircle, { className: "text-red-600", size: 20 })), _jsx("h3", { className: `font-bold ${isValid ? "text-green-900" : "text-red-900"}`, children: "Compliance Report" })] }), _jsx("span", { className: `px-2 py-0.5 rounded-full text-xs font-bold uppercase ${isValid ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"}`, children: isValid ? "PASSED" : "ACTION REQUIRED" })] }), _jsxs("div", { className: "p-4 space-y-4", children: [_jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsx(CheckItem, { label: "Legal Policies", status: checks.legalPolicies }), _jsx(CheckItem, { label: "Product Readiness", status: checks.productReadiness }), _jsx(CheckItem, { label: "Branding Settings", status: checks.brandingReadiness }), _jsx(CheckItem, { label: "Content Moderation", status: checks.contentModeration })] }), !isValid && (_jsxs("div", { className: "mt-4 p-3 bg-gray-50 rounded-lg border border-gray-100", children: [_jsx("h4", { className: "text-xs font-bold text-gray-500 uppercase mb-2", children: "Detailed Findings" }), _jsxs("ul", { className: "space-y-2", children: [!checks.legalPolicies && (_jsxs("li", { className: "flex items-start gap-2 text-sm text-gray-700", children: [_jsx(XCircle, { size: 14, className: "text-red-500 mt-0.5 flex-shrink-0" }), _jsxs("span", { children: ["Missing mandatory policies: ", _jsx("span", { className: "font-medium", children: details.missingPolicies.join(", ") })] })] })), !checks.productReadiness && (_jsxs("li", { className: "flex items-start gap-2 text-sm text-gray-700", children: [_jsx(XCircle, { size: 14, className: "text-red-500 mt-0.5 flex-shrink-0" }), _jsx("span", { children: "No active products found. Store must have at least 1 active product." })] })), !checks.contentModeration && (_jsxs("li", { className: "flex items-start gap-2 text-sm text-gray-700", children: [_jsx(XCircle, { size: 14, className: "text-red-500 mt-0.5 flex-shrink-0" }), _jsxs("span", { children: ["Prohibited content found: ", _jsx("span", { className: "font-medium", children: details.prohibitedWordsFound.join(", ") })] })] })), !checks.brandingReadiness && (_jsxs("li", { className: "flex items-start gap-2 text-sm text-gray-700", children: [_jsx(Info, { size: 14, className: "text-blue-500 mt-0.5 flex-shrink-0" }), _jsx("span", { children: "Logo or Banner is missing. Highly recommended for a premium experience." })] }))] })] }))] })] }));
}
function CheckItem({ label, status }) {
    return (_jsxs("div", { className: "flex items-center gap-2", children: [status ? (_jsx(CheckCircle, { className: "text-green-500", size: 16 })) : (_jsx(XCircle, { className: "text-red-400", size: 16 })), _jsx("span", { className: `text-sm ${status ? "text-gray-700" : "text-gray-500"}`, children: label })] }));
}
