import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import NextLink from "next/link";
const Link = NextLink;
import Image from "next/image";
import { Clock, Flame } from "lucide-react";
import { Button } from "@vayva/ui";
export function FoodProductCard({ product, storeSlug }) {
    const metadata = product.metadata; // Safe cast for variant fields
    return (_jsxs("div", { className: "flex gap-4 border-b border-gray-100 py-4 group", children: [_jsx(Link, { href: `/products/${product.id}?store=${storeSlug}`, className: "relative h-24 w-24 flex-shrink-0 rounded-lg overflow-hidden bg-gray-100", children: product.images[0] ? (_jsx(Image, { src: product.images[0], alt: product.name, fill: true, sizes: "96px", className: "object-cover group-hover:scale-105 transition-transform" })) : (_jsx("div", { className: "w-full h-full flex items-center justify-center text-xs text-gray-400", children: "No Image" })) }), _jsxs("div", { className: "flex-1 flex flex-col justify-between", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsx(Link, { href: `/products/${product.id}?store=${storeSlug}`, children: _jsx("h3", { className: "font-semibold text-gray-900 group-hover:text-amber-600 transition-colors", children: product.name }) }), _jsxs("span", { className: "font-bold text-sm", children: ["\u20A6", product.price.toLocaleString()] })] }), _jsx("p", { className: "text-sm text-gray-500 line-clamp-2 mt-1", children: product.description })] }), _jsxs("div", { className: "flex items-center gap-3 text-xs text-gray-500 mt-2", children: [metadata?.prepTimeMinutes && (_jsxs("div", { className: "flex items-center gap-1", children: [_jsx(Clock, { className: "w-3 h-3" }), _jsxs("span", { children: [metadata.prepTimeMinutes, "m"] })] })), metadata?.spiceLevel && metadata.spiceLevel !== "MILD" && (_jsxs("div", { className: "flex items-center gap-1 text-red-500", children: [_jsx(Flame, { className: "w-3 h-3" }), _jsx("span", { children: metadata.spiceLevel })] })), metadata?.isVegetarian && (_jsx("span", { className: "px-1.5 py-0.5 rounded-full bg-green-100 text-green-700 font-medium", children: "Veg" }))] })] }), _jsx(Button, { variant: "outline", size: "icon", className: "flex items-center justify-center h-8 w-8 rounded-full border border-gray-200 text-gray-600 hover:bg-amber-600 hover:text-white hover:border-amber-600 transition-all self-center h-auto", "aria-label": `Add ${product.name} to cart`, children: "+" })] }));
}
