"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button, cn } from "@vayva/ui";
import Link from "next/link";
export function MarketingFooter() {
    return (_jsxs("footer", { className: "bg-white text-[#0F172A] border-t border-slate-100", children: [_jsx("div", { className: "max-w-7xl mx-auto px-6 py-16", children: _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-12", children: [_jsxs("div", { className: "col-span-2 md:col-span-1", children: [_jsx("div", { className: "mb-4", children: _jsx(Link, { href: "/", className: "inline-block hover:opacity-80 transition-opacity", children: _jsx("span", { className: "text-xl font-bold text-[#0F172A] tracking-tighter", children: "Vayva" }) }) }), _jsx("p", { className: "text-xs text-slate-500 leading-relaxed font-medium max-w-[200px]", children: "The operating system for commerce on WhatsApp. Turning conversations into reliable business records." })] }), _jsxs("div", { className: "space-y-6", children: [_jsx("h4", { className: "text-[10px] font-black text-[#0F172A] uppercase tracking-[0.2em]", children: "Product" }), _jsx("ul", { className: "space-y-3", children: [
                                        { label: "How Vayva Works", href: "/how-it-works" },
                                        { label: "Pricing Plans", href: "/pricing" },
                                        { label: "Store Builder", href: "/store-builder" },
                                        { label: "Marketplace", href: "https://marketplace.vayva.app" }
                                    ].map((link) => (_jsx("li", { children: _jsx(Link, { href: link.href, className: "text-xs font-semibold text-slate-500 hover:text-[#22C55E] transition-colors", children: link.label }) }, link.label))) })] }), _jsxs("div", { className: "space-y-6", children: [_jsx("h4", { className: "text-[10px] font-black text-[#0F172A] uppercase tracking-[0.2em]", children: "Company" }), _jsx("ul", { className: "space-y-3", children: [
                                        { label: "About Vayva", href: "/about" },
                                        { label: "Our Blog", href: "/blog" },
                                        { label: "Contact Us", href: "/contact" }
                                    ].map((link) => (_jsx("li", { children: _jsx(Link, { href: link.href, className: "text-xs font-semibold text-slate-500 hover:text-[#22C55E] transition-colors", children: link.label }) }, link.label))) })] }), _jsxs("div", { className: "space-y-6", children: [_jsx("h4", { className: "text-[10px] font-black text-[#0F172A] uppercase tracking-[0.2em]", children: "Resources" }), _jsx("ul", { className: "space-y-3", children: [
                                        { label: "Help Center", href: "/help" },
                                        { label: "System Status", href: "/system-status" },
                                        { label: "Trust & Security", href: "/trust" }
                                    ].map((link) => (_jsx("li", { children: _jsx(Link, { href: link.href, className: "text-xs font-semibold text-slate-500 hover:text-[#22C55E] transition-colors", children: link.label }) }, link.label))) })] }), _jsxs("div", { className: "space-y-6", children: [_jsx("h4", { className: "text-[10px] font-black text-[#0F172A] uppercase tracking-[0.2em]", children: "Legal" }), _jsx("ul", { className: "space-y-3", children: [
                                        { label: "Legal Hub", href: "/legal" },
                                        { label: "Privacy Policy", href: "/legal/privacy" },
                                        { label: "Terms of Service", href: "/legal/terms" }
                                    ].map((link) => (_jsx("li", { children: _jsx(Link, { href: link.href, className: "text-xs font-semibold text-slate-500 hover:text-[#22C55E] transition-colors", children: link.label }) }, link.label))) })] })] }) }), _jsx("div", { className: "border-t border-slate-50 py-8", children: _jsxs("div", { className: "max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-6", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("p", { className: "text-[10px] text-slate-400 font-bold uppercase tracking-widest", children: "\u00A9 2025 Vayva Tech" }), _jsx("div", { className: "h-4 w-[1px] bg-slate-100 hidden md:block" }), _jsxs("div", { className: "flex items-center px-3 py-1 rounded-full bg-slate-50 border border-slate-100", children: [_jsx("span", { className: "w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse mr-2" }), _jsx("span", { className: "text-[9px] font-black uppercase tracking-widest text-[#64748B]", children: "Vayva Merchant v1.0" })] })] }), _jsxs("div", { className: "flex items-center gap-8", children: [_jsx(Link, { href: "/legal", className: "text-[10px] font-black text-slate-400 hover:text-[#22C55E] transition-all uppercase tracking-[0.2em]", children: "Legal Hub" }), _jsx("div", { className: "flex gap-4", children: ["Twitter", "LinkedIn", "Instagram"].map((social) => (_jsx(Button, { className: "text-slate-300 hover:text-black transition-colors", "aria-label": social, children: _jsx("div", { className: cn("w-4 h-4 bg-current", `[mask-image:url(/icons/${social.toLowerCase()}.svg)]`, "[mask-repeat:no-repeat]", "[mask-position:center]") }) }, social))) })] })] }) })] }));
}
