"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Link from "next/link";
import { Icon, cn, Button } from "@vayva/ui";
export const LaunchChecklist = ({ items }) => {
    // Interactive progress
    const completedCount = items.filter((i) => i.isCompleted).length;
    const progress = Math.round((completedCount / items.length) * 100);
    return (_jsxs("div", { className: "bg-[#142210] border border-primary/20 rounded-2xl p-6 mb-8 relative overflow-hidden", children: [_jsx("div", { className: "absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full blur-3xl translate-x-1/2 -translate-y-1/2 pointer-events-none" }), _jsxs("div", { className: "flex items-start justify-between mb-6 relative z-10", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold text-white mb-1", children: "Let's get your store ready for launch \uD83D\uDE80" }), _jsx("p", { className: "text-text-secondary text-sm", children: "Complete these steps to start accepting real orders." })] }), _jsxs("div", { className: "flex items-center gap-3 bg-black/20 p-2 rounded-lg border border-white/5", children: [_jsxs("div", { className: "text-right", children: [_jsx("p", { className: "text-xs text-text-secondary", children: "Progress" }), _jsxs("p", { className: "text-sm font-bold text-white", children: [progress, "% Ready"] })] }), _jsx("div", { className: "w-10 h-10 relative flex items-center justify-center", children: _jsxs("svg", { className: "w-full h-full -rotate-90", viewBox: "0 0 36 36", children: [_jsx("path", { className: "text-white/10", d: "M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831", fill: "none", stroke: "currentColor", strokeWidth: "4" }), _jsx("path", { className: "text-primary transition-all duration-1000 ease-out", strokeDasharray: `${progress}, 100`, d: "M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831", fill: "none", stroke: "currentColor", strokeWidth: "4" })] }) })] })] }), _jsx("div", { className: "grid gap-3 relative z-10", children: items.map((item, idx) => (_jsxs("div", { className: cn("flex items-center justify-between p-4 rounded-xl border transition-all", item.isCompleted
                        ? "bg-primary/5 border-primary/20 opacity-60 hover:opacity-100"
                        : "bg-white/5 border-white/5 hover:bg-white/10 hover:border-white/10"), children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: cn("w-6 h-6 rounded-full flex items-center justify-center border transition-colors", item.isCompleted
                                        ? "bg-primary border-primary text-black"
                                        : "border-white/30 text-transparent"), children: _jsx(Icon, { name: "Check", size: 14, strokeWidth: 4 }) }), _jsxs("div", { children: [_jsx("h4", { className: cn("font-medium text-sm", item.isCompleted
                                                ? "text-primary line-through decoration-primary/50"
                                                : "text-white"), children: item.label }), !item.isCompleted && (_jsx("p", { className: "text-xs text-text-secondary mt-0.5", children: item.description }))] })] }), !item.isCompleted && (_jsx(Link, { href: item.href, children: _jsxs(Button, { className: "h-8 px-4 rounded-lg bg-white/10 hover:bg-white/20 text-white text-xs font-medium transition-colors flex items-center gap-2", variant: "ghost", children: [item.cta, _jsx(Icon, { name: "ArrowRight", size: 12 })] }) }))] }, item.id))) })] }));
};
