import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@vayva/ui";
export const PharmacyHealthTemplate = ({ businessName, demoMode, }) => {
    return (_jsxs("div", { className: "font-sans min-h-screen bg-emerald-50 text-emerald-900 pb-20", children: [_jsxs("header", { className: "bg-white px-6 py-4 flex justify-between items-center shadow-sm sticky top-0 z-50", children: [_jsxs("div", { className: "flex items-center gap-2 font-bold text-xl text-emerald-700", children: [_jsx("span", { className: "text-2xl", children: "\u271A" }), businessName || "LifeCare Pharmacy"] }), _jsxs("div", { className: "flex gap-4 items-center", children: [_jsx("span", { className: "bg-emerald-100 text-emerald-800 px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wide", children: "License #10293" }), _jsx(Button, { className: "bg-emerald-600 text-white px-4 py-2 rounded-lg text-xs font-bold hover:bg-emerald-700 h-auto", children: "Upload Prescription" })] })] }), _jsxs("div", { className: "bg-emerald-700 text-white p-8 text-center rounded-b-3xl mb-8 shadow-xl shadow-emerald-900/10", children: [_jsx("h1", { className: "text-2xl font-bold mb-2", children: "Your family's health, first." }), _jsx("p", { className: "text-sm text-emerald-100 mb-6", children: "Genuine drugs. Expert advice. Fast delivery." }), _jsxs("div", { className: "relative max-w-lg mx-auto", children: [_jsx("input", { type: "text", placeholder: "Search for medications (e.g. Panadol, Malaria)", className: "w-full py-4 px-6 rounded-full text-gray-900 font-medium shadow-lg outline-none focus:ring-4 focus:ring-emerald-500/30" }), _jsx(Button, { size: "icon", className: "absolute right-2 top-2 bg-emerald-600 p-2 rounded-full text-white hover:bg-emerald-500 h-auto w-auto", children: _jsx("svg", { className: "w-6 h-6", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" }) }) })] })] }), _jsx("section", { className: "px-6 mb-8", children: _jsx("div", { className: "flex gap-4 overflow-x-auto pb-4", children: [
                        "Baby Care",
                        "Malaria",
                        "Vitamins",
                        "Sexual Health",
                        "First Aid",
                    ].map((cat) => (_jsxs("div", { className: "bg-white min-w-[120px] p-4 rounded-xl shadow-sm text-center cursor-pointer hover:shadow-md transition-shadow", children: [_jsx("div", { className: "text-2xl mb-2", children: "\uD83D\uDC8A" }), _jsx("div", { className: "text-xs font-bold", children: cat })] }, cat))) }) }), _jsx("section", { className: "px-6", children: _jsxs("div", { className: "bg-white rounded-xl p-6 flex items-start gap-4 border border-emerald-100 shadow-sm relative overflow-hidden", children: [_jsx("div", { className: "w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center text-3xl z-10", children: "\uD83D\uDC68\uD83C\uDFFE\u200D\u2695\uFE0F" }), _jsxs("div", { className: "flex-1 z-10", children: [_jsx("h3", { className: "font-bold text-lg text-emerald-800 mb-1", children: "Speak to a Pharmacist" }), _jsx("p", { className: "text-xs text-gray-500 mb-3 leading-relaxed", children: "Not sure what you need? Our licensed pharmacists are available for a private chat." }), _jsx(Button, { className: "text-xs font-bold text-white bg-emerald-600 px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-emerald-700 h-auto", children: "Start Chat" })] }), _jsx("div", { className: "absolute right-[-20px] bottom-[-20px] text-[150px] opacity-5 text-emerald-900 select-none pointer-events-none", children: "\uD83D\uDCAC" })] }) })] }));
};
