"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from "react";
import Link from "next/link";
import { StoreShell } from "@/components/storefront/store-shell";
import { Button, Icon } from "@vayva/ui";
const DEMO_PRODUCT = {
    id: "1",
    name: "Premium Cotton Tee",
    price: 12000,
    curr: "₦",
    desc: "Crafted from 100% organic cotton, this tee offers a relaxed fit and breathable comfort for all-day wear. An essential for any wardrobe.",
    images: ["", "", ""],
    colors: ["Black", "White", "Navy"],
    sizes: ["S", "M", "L", "XL"],
};
export default function ProductDetailPage({ params, }) {
    const { slug, id } = React.use(params);
    const [selectedColor, setSelectedColor] = useState(DEMO_PRODUCT.colors[0]);
    const [selectedSize, setSelectedSize] = useState(DEMO_PRODUCT.sizes[1]);
    const [qty, setQty] = useState(1);
    return (_jsx(StoreShell, { slug: slug, children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 py-8 md:py-16", children: [_jsxs("div", { className: "text-xs text-text-secondary uppercase font-bold tracking-wider mb-8 flex items-center gap-2", children: [_jsx(Link, { href: `/store/${slug}`, className: "hover:text-white", children: "Home" }), _jsx(Icon, { name: "ChevronRight", size: 14 }), _jsx(Link, { href: `/store/${slug}/collections/all`, className: "hover:text-white", children: "Products" }), _jsx(Icon, { name: "ChevronRight", size: 14 }), _jsx("span", { className: "text-white", children: DEMO_PRODUCT.name })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-12 lg:gap-20", children: [_jsxs("div", { className: "space-y-4", children: [_jsx("div", { className: "aspect-[4/5] bg-white/5 rounded-2xl w-full relative overflow-hidden flex items-center justify-center", children: _jsx(Icon, { name: "Image", size: 64, className: "text-white/10" }) }), _jsx("div", { className: "grid grid-cols-4 gap-4", children: [1, 2, 3, 4].map((i) => (_jsx("div", { className: "aspect-square bg-white/5 rounded-lg cursor-pointer hover:bg-white/10 transition-colors" }, i))) })] }), _jsxs("div", { children: [_jsx("h1", { className: "text-3xl md:text-4xl font-bold text-white mb-4", children: DEMO_PRODUCT.name }), _jsxs("div", { className: "text-2xl font-bold text-white mb-8", children: [DEMO_PRODUCT.curr, " ", DEMO_PRODUCT.price.toLocaleString()] }), _jsxs("div", { className: "space-y-8 mb-10", children: [_jsxs("div", { children: [_jsxs("label", { className: "text-xs text-text-secondary uppercase font-bold tracking-wider mb-3 block", children: ["Color: ", _jsx("span", { className: "text-white", children: selectedColor })] }), _jsx("div", { className: "flex gap-3", children: DEMO_PRODUCT.colors.map((color) => (_jsx("div", { onClick: () => setSelectedColor(color), className: `w-10 h-10 rounded-full cursor-pointer flex items-center justify-center border-2 transition-all
                                                ${selectedColor === color ? "border-primary" : "border-transparent hover:border-white/20"}
                                                ${color === "White" ? "bg-white" : color === "Black" ? "bg-gray-900" : "bg-blue-900"}
                                            `, children: selectedColor === color && (_jsx(Icon, { name: "Check", size: 16, className: color === "White" ? "text-black" : "text-white" })) }, color))) })] }), _jsxs("div", { children: [_jsxs("label", { className: "text-xs text-text-secondary uppercase font-bold tracking-wider mb-3 block", children: ["Size: ", _jsx("span", { className: "text-white", children: selectedSize })] }), _jsx("div", { className: "flex gap-3", children: DEMO_PRODUCT.sizes.map((size) => (_jsx("div", { onClick: () => setSelectedSize(size), className: `w-12 h-10 rounded-lg flex items-center justify-center text-sm font-bold cursor-pointer transition-colors border
                                                ${selectedSize === size ? "bg-primary text-black border-primary" : "bg-white/5 text-white border-white/10 hover:border-white/30"}
                                            `, children: size }, size))) })] }), _jsxs("div", { className: "flex gap-4", children: [_jsxs("div", { className: "flex items-center bg-white/5 border border-white/10 rounded-full h-12 px-2", children: [_jsx(Button, { onClick: () => setQty(Math.max(1, qty - 1)), className: "w-8 h-full flex items-center justify-center text-white/50 hover:text-white", children: _jsx(Icon, { name: "Minus", size: 16 }) }), _jsx("span", { className: "w-8 text-center text-white font-bold", children: qty }), _jsx(Button, { onClick: () => setQty(qty + 1), className: "w-8 h-full flex items-center justify-center text-white/50 hover:text-white", children: _jsx(Icon, { name: "Plus", size: 16 }) })] }), _jsx(Button, { className: "flex-1 h-12 rounded-full bg-primary text-black hover:bg-primary/90 font-bold text-base shadow-[0_0_20px_rgba(70,236,19,0.2)]", children: "Add to Cart" })] }), _jsxs(Button, { variant: "outline", className: "w-full h-12 rounded-full border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/10 hover:text-emerald-300 gap-2", children: [_jsx(Icon, { name: "MessageCircle" }), " Chat on WhatsApp about this item"] })] }), _jsxs("div", { className: "border-t border-white/10 divide-y divide-white/10", children: [_jsxs("div", { className: "py-4", children: [_jsx("h3", { className: "font-bold text-white mb-2 text-sm", children: "Description" }), _jsx("p", { className: "text-sm text-text-secondary leading-relaxed", children: DEMO_PRODUCT.desc })] }), _jsx("div", { className: "py-4", children: _jsxs("div", { className: "flex justify-between items-center cursor-pointer group", children: [_jsx("h3", { className: "font-bold text-white text-sm group-hover:text-primary transition-colors", children: "Delivery & Returns" }), _jsx(Icon, { name: "Plus", size: 18, className: "text-text-secondary" })] }) })] })] })] })] }) }));
}
