import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button, Icon, cn } from "@vayva/ui";
export const DomainSettings = ({ domains, onAddDomain, }) => {
    return (_jsxs("section", { className: "mb-12", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-bold text-gray-900", children: "Domains & Website" }), _jsx("p", { className: "text-sm text-gray-500", children: "Control how customers access your store." })] }), _jsxs(Button, { variant: "outline", size: "sm", onClick: onAddDomain, className: "gap-2", children: [_jsx(Icon, { name: "Plus", size: 16 }), " Add Custom Domain"] })] }), _jsx("div", { className: "bg-white rounded-2xl border border-gray-200 divide-y divide-gray-100 overflow-hidden", children: domains.map((domain) => (_jsxs("div", { className: "p-5 flex flex-col md:flex-row md:items-center justify-between gap-4", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: cn("w-10 h-10 rounded-full flex items-center justify-center shrink-0", domain.status === "active"
                                        ? "bg-green-50 text-green-600"
                                        : domain.status === "connecting"
                                            ? "bg-blue-50 text-blue-600 animate-pulse"
                                            : "bg-red-50 text-red-600"), children: _jsx(Icon, { name: domain.type === "subdomain" ? "Globe" : "Link", size: 20 }) }), _jsxs("div", { children: [_jsxs("h4", { className: "font-bold text-gray-900 flex items-center gap-2", children: [domain.name, domain.type === "subdomain" && (_jsx("span", { className: "text-[10px] bg-gray-100 text-gray-500 px-2 py-0.5 rounded-full font-bold uppercase tracking-wider", children: "Default" }))] }), _jsxs("div", { className: "flex items-center gap-3 mt-1 text-xs", children: [_jsxs("span", { className: cn("flex items-center gap-1 font-medium", domain.status === "active"
                                                        ? "text-green-600"
                                                        : "text-amber-600"), children: [_jsx("div", { className: cn("w-1.5 h-1.5 rounded-full bg-current", domain.status !== "active" && "animate-pulse") }), domain.status === "active" ? "Active" : "Connecting..."] }), _jsx("span", { className: "text-gray-300", children: "|" }), _jsxs("span", { className: "text-gray-500 flex items-center gap-1", children: [_jsx(Icon, { name: domain.sslStatus === "active" ? "Lock" : "LockOpen", size: 10 }), "SSL ", domain.sslStatus === "active" ? "Secured" : "Pending"] })] })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [domain.status === "connecting" && (_jsx(Button, { size: "sm", variant: "ghost", className: "text-blue-600 bg-blue-50 hover:bg-blue-100", children: "Verify DNS" })), _jsx(Button, { size: "sm", variant: "outline", className: "text-gray-500", children: "Manage" })] })] }, domain.id))) })] }));
};
