import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Icon, cn, Button } from "@vayva/ui";
export const OptimizationHub = ({ status, onToggleActive, }) => {
    const [loading, setLoading] = useState(false);
    const handleToggle = async () => {
        setLoading(true);
        try {
            await onToggleActive(!status.active);
        }
        finally {
            setLoading(false);
        }
    };
    return (_jsxs("div", { className: "bg-white border border-gray-200 rounded-2xl p-6 shadow-sm", children: [_jsxs("div", { className: "flex items-start justify-between mb-6", children: [_jsxs("div", { children: [_jsxs("h3", { className: "text-lg font-bold text-gray-900 flex items-center gap-2", children: [_jsx(Icon, { name: "Zap", size: 20, className: status.active ? "text-amber-500" : "text-gray-400" }), "Auto-Optimization"] }), _jsx("p", { className: "text-sm text-gray-500 mt-1", children: "Automatically improve mobile layout and checkout flow." })] }), _jsx(Button, { onClick: handleToggle, disabled: loading, className: cn("relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none", status.active ? "bg-amber-500" : "bg-gray-200"), children: _jsx("span", { className: cn("pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out", status.active ? "translate-x-5" : "translate-x-0") }) })] }), status.active ? (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex gap-4 p-4 bg-amber-50 border border-amber-100 rounded-xl", children: [_jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "text-xs font-bold text-amber-800 uppercase tracking-wide mb-1", children: "Impact" }), _jsxs("p", { className: "text-2xl font-bold text-amber-900", children: ["+", status.metrics.uplift_rate, "%"] }), _jsx("p", { className: "text-xs text-amber-700", children: "Conversion Uplift" })] }), _jsx("div", { className: "w-px bg-amber-200" }), _jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "text-xs font-bold text-amber-800 uppercase tracking-wide mb-1", children: "Safety" }), _jsxs("p", { className: "text-2xl font-bold text-amber-900", children: [status.metrics.prevented_dropoff, "%"] }), _jsx("p", { className: "text-xs text-amber-700", children: "Drop-off Prevented" })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "text-xs font-bold text-gray-500 uppercase", children: "Active Rules Applied" }), status.applied_rules.map((rule) => (_jsxs("div", { className: "flex items-center justify-between p-3 bg-gray-50 rounded-lg border border-gray-100", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Icon, { name: rule.type === "mobile" ? "Smartphone" : "ShoppingCart", size: 14, className: "text-gray-400" }), _jsx("span", { className: "text-sm font-medium text-gray-900", children: rule.name })] }), _jsxs("span", { className: cn("text-[10px] uppercase font-bold px-1.5 py-0.5 rounded", rule.impact === "high"
                                            ? "bg-green-100 text-green-700"
                                            : "bg-gray-100 text-gray-600"), children: [rule.impact, " Impact"] })] }, rule.id)))] }), _jsx(Button, { size: "sm", className: "text-gray-400 underline decoration-dotted hover:text-gray-600", children: "Revert all changes" })] })) : (_jsxs("div", { className: "text-center py-6 bg-gray-50 rounded-xl border border-dashed border-gray-200", children: [_jsx("p", { className: "text-sm text-gray-500 mb-2", children: "Auto-Optimization is paused." }), _jsx(Button, { onClick: handleToggle, className: "text-sm text-amber-600 hover:text-amber-700", children: "Turn On \u2192" })] }))] }));
};
