import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Icon, cn, Button } from "@vayva/ui";
import { TemplateMiniPreview } from "./TemplateMiniPreview";
export const TemplateCard = ({ template, onPreview, onUse, onUnlock, userPlan, recommendation, compact, }) => {
    // Determine if locked based on plan
    const planLevels = ["free", "growth", "pro"];
    const userLevelIndex = planLevels.indexOf(userPlan);
    const requiredLevelIndex = planLevels.indexOf(template.tier);
    const isPlanLocked = requiredLevelIndex > userLevelIndex;
    const isLocked = template.isLocked || isPlanLocked;
    return (_jsxs("div", { className: cn("group bg-white border rounded-2xl overflow-hidden hover:shadow-xl transition-all duration-300 flex flex-col h-full", recommendation
            ? "border-purple-200 ring-2 ring-purple-100"
            : "border-gray-200"), children: [recommendation && (_jsxs("div", { className: "bg-purple-50 px-4 py-2 flex items-center gap-2 border-b border-purple-100", children: [_jsx(Icon, { name: "Sparkles", size: 14, className: "text-purple-600" }), _jsx("span", { className: "text-xs font-bold text-purple-900 line-clamp-1", children: recommendation.reason }), _jsx("span", { className: "ml-auto text-[10px] font-bold bg-white text-purple-700 px-2 py-0.5 rounded-full border border-purple-200", children: recommendation.expectedImpact })] })), _jsxs("div", { className: "relative aspect-[4/3] bg-gray-100 overflow-hidden cursor-pointer", onClick: () => onPreview(template), children: [template.layoutComponent ? (_jsx("div", { className: "w-full h-full group-hover:scale-105 transition-transform duration-700", children: _jsx(TemplateMiniPreview, { layoutComponent: template.layoutComponent, templateName: template.name, componentProps: template.componentProps }) })) : (_jsx("img", { src: template.previewImageDesktop ||
                            template.previewImages?.cover ||
                            "/images/template-previews/default-desktop.png", alt: template.name, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-700", onError: (e) => {
                            e.target.src =
                                "/images/template-previews/default-desktop.png";
                        } })), _jsxs("div", { className: "absolute top-3 left-3 flex flex-col gap-1", children: [template.isActive && (_jsx("span", { className: "bg-green-500 text-white text-[10px] font-bold px-2 py-0.5 rounded-md uppercase tracking-wide shadow-sm", children: "Active" })), isLocked && (_jsxs("span", { className: "bg-gray-900/90 text-white text-[10px] font-bold px-2 py-0.5 rounded-md uppercase tracking-wide shadow-sm flex items-center gap-1", children: [_jsx(Icon, { name: "Lock", size: 10 }), " ", template.tier, " Plan"] }))] }), _jsx("div", { className: "absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-3 backdrop-blur-[2px]", children: _jsxs(Button, { onClick: (e) => {
                                e.stopPropagation();
                                onPreview(template);
                            }, variant: "ghost", className: "bg-white text-black px-4 py-2 rounded-xl text-xs font-bold shadow-lg transform translate-y-2 group-hover:translate-y-0 transition-transform duration-300 hover:bg-gray-50 flex items-center gap-2", children: [_jsx(Icon, { name: "Eye", size: 14 }), " Preview"] }) })] }), _jsxs("div", { className: "p-5 flex flex-col flex-1", children: [_jsx("div", { className: "flex justify-between items-start mb-2", children: _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [template.demand === "popular" && (_jsxs("span", { className: "text-[9px] font-black uppercase tracking-wider text-orange-600 bg-orange-50 px-1.5 py-0.5 rounded border border-orange-100 flex items-center gap-1", children: [_jsx(Icon, { name: "Flame", size: 8 }), " Popular"] })), template.demand === "high_demand" && (_jsx("span", { className: "text-[9px] font-bold uppercase tracking-wider text-blue-600 bg-blue-50 px-1.5 py-0.5 rounded border border-blue-100", children: "High Demand" })), _jsxs("span", { className: "text-[9px] font-medium text-gray-400 flex items-center gap-1", children: [_jsx(Icon, { name: "Clock", size: 8 }), " ", template.setupTime] })] }), _jsx("h3", { className: "font-heading font-bold text-lg text-gray-900 leading-tight", children: template.name }), template.tagline && (_jsx("p", { className: "text-xs font-medium text-purple-600 mt-0.5", children: template.tagline })), _jsx("p", { className: "text-xs text-gray-500 mt-1 line-clamp-2", children: template.description })] }) }), _jsx("div", { className: "flex flex-wrap gap-1 mb-4", children: template.tags.slice(0, 3).map((tag) => (_jsx("span", { className: "text-[10px] bg-gray-50 text-gray-500 px-2 py-1 rounded-md border border-gray-100 font-medium", children: tag }, tag))) }), _jsxs("div", { className: "mt-auto pt-4 border-t border-gray-100 space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between text-xs", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: cn("px-1.5 py-0.5 rounded text-[10px] uppercase font-bold border", template.tier === "free"
                                                    ? "bg-gray-50 text-gray-600 border-gray-200"
                                                    : template.tier === "growth"
                                                        ? "bg-blue-50 text-blue-600 border-blue-200"
                                                        : "bg-purple-50 text-purple-600 border-purple-200"), children: template.tier }), _jsx("span", { className: "text-gray-300", children: "|" }), _jsxs("span", { className: "text-gray-500 font-medium capitalize flex items-center gap-1", children: [template.checkoutMode === "whatsapp" && (_jsx(Icon, { name: "MessageCircle", size: 10 })), template.checkoutMode === "website" && (_jsx(Icon, { name: "Globe", size: 10 })), template.checkoutMode === "hybrid" && (_jsx(Icon, { name: "Shuffle", size: 10 })), template.checkoutMode] })] }), template.price > 0 &&
                                        !template.isPurchased &&
                                        !template.isActive ? (_jsxs("span", { className: "font-bold text-gray-900", children: ["\u20A6", template.price.toLocaleString()] })) : null] }), template.isActive ? (_jsxs(Button, { className: "w-full py-2.5 bg-gray-100 text-gray-400 rounded-xl text-sm font-bold cursor-default flex items-center justify-center gap-2", variant: "ghost", children: [_jsx(Icon, { name: "Check", size: 16 }), " Active on Store"] })) : isLocked ? (_jsxs(Button, { onClick: () => onUnlock?.(template), variant: "primary", className: "w-full py-2.5 bg-gray-900 text-white rounded-xl text-sm font-bold hover:bg-gray-800 transition-colors flex items-center justify-center gap-2", children: [_jsx(Icon, { name: "Lock", size: 14 }), " Unlock with ", template.tier] })) : template.price > 0 && !template.isPurchased ? (_jsxs(Button, { onClick: () => onUse(template), variant: "primary", className: "w-full py-2.5 bg-black text-white rounded-xl text-sm font-bold hover:bg-gray-800 transition-colors shadow-sm group-hover:shadow-md flex items-center justify-center gap-2", children: [_jsx(Icon, { name: "CreditCard", size: 14 }), " Buy Template"] })) : (_jsx(Button, { onClick: () => onUse(template), variant: "primary", className: "w-full py-2.5 bg-black text-white rounded-xl text-sm font-bold hover:bg-gray-800 transition-colors shadow-sm group-hover:shadow-md", children: "Use Template" }))] })] })] }));
};
