import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Icon, cn, Button } from "@vayva/ui";
export const UsageAndSystem = ({ usage, systemStatus, }) => {
    const renderProgressBar = (metric) => {
        const percentage = metric.limit === "unlimited" ? 0 : (metric.used / metric.limit) * 100;
        const isNearLimit = typeof metric.limit === "number" && percentage > 80;
        return (_jsxs("div", { className: "mb-4 last:mb-0", children: [_jsxs("div", { className: "flex justify-between text-sm mb-1.5", children: [_jsx("span", { className: "font-medium text-gray-700", children: metric.label }), _jsxs("span", { className: "text-gray-500", children: [_jsx("strong", { className: "text-gray-900", children: metric.used }), " /", " ", metric.limit === "unlimited" ? "∞" : metric.limit] })] }), _jsx("div", { className: "h-2 w-full bg-gray-100 rounded-full overflow-hidden", children: _jsx("div", { className: cn("h-full rounded-full transition-all duration-500", isNearLimit ? "bg-amber-500" : "bg-black"), style: { width: `${Math.min(percentage, 100)}%` } }) })] }));
    };
    return (_jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-8 pb-12", children: [_jsxs("div", { className: "lg:col-span-1", children: [_jsx("h3", { className: "text-sm font-bold text-gray-900 uppercase tracking-widest mb-4", children: "Plan Usage" }), _jsxs("div", { className: "bg-white rounded-2xl border border-gray-200 p-6", children: [renderProgressBar(usage.orders), renderProgressBar(usage.products), renderProgressBar(usage.templates), _jsx(Button, { variant: "primary", className: "w-full mt-6 py-2 text-sm text-indigo-600 hover:text-indigo-700 hover:bg-indigo-50", children: "View Plan Details" })] })] }), _jsxs("div", { className: "lg:col-span-2", children: [_jsx("h3", { className: "text-sm font-bold text-gray-900 uppercase tracking-widest mb-4", children: "System Status Reference" }), systemStatus.issues.length === 0 ? (_jsxs("div", { className: "bg-green-50 rounded-2xl border border-green-100 p-6 flex items-center gap-4", children: [_jsx("div", { className: "w-12 h-12 rounded-full bg-green-100 text-green-600 flex items-center justify-center shrink-0", children: _jsx(Icon, { name: "Check", size: 24 }) }), _jsxs("div", { children: [_jsx("h4", { className: "font-bold text-green-900", children: "All Systems Operational" }), _jsx("p", { className: "text-green-700 text-sm mt-1", children: "Website, checkout, and integrations are running smoothly." })] })] })) : (_jsx("div", { className: "space-y-3", children: systemStatus.issues.map((issue) => (_jsxs("div", { className: cn("rounded-xl border p-4 flex items-start gap-4", issue.severity === "critical"
                                ? "bg-red-50 border-red-100"
                                : "bg-amber-50 border-amber-100"), children: [_jsx("div", { className: cn("mt-0.5", issue.severity === "critical"
                                        ? "text-red-600"
                                        : "text-amber-600"), children: _jsx(Icon, { name: issue.severity === "critical" ? "X" : "Info", size: 20 }) }), _jsxs("div", { className: "flex-1", children: [_jsx("p", { className: cn("text-sm font-bold mb-0.5", issue.severity === "critical"
                                                ? "text-red-900"
                                                : "text-amber-900"), children: issue.message }), issue.actionUrl && (_jsx("a", { href: issue.actionUrl, className: "text-xs font-bold underline hover:no-underline opacity-80 hover:opacity-100 transition-opacity", children: "Fix Issue" }))] })] }, issue.id))) }))] })] }));
};
