export const PERMISSIONS = {
    TEAM_MANAGE: "team:manage",
    FINANCE_VIEW: "finance:view",
    REFUNDS_MANAGE: "refunds:manage",
    SETTINGS_VIEW: "settings:view",
    SETTINGS_EDIT: "settings:edit",
    PAYOUTS_MANAGE: "payouts:manage",
    DOMAINS_MANAGE: "domains:manage",
    INTEGRATIONS_MANAGE: "integrations:manage",
    TEMPLATES_MANAGE: "templates:manage",
    KYC_MANAGE: "kyc:manage",
    BILLING_MANAGE: "billing:manage",
    COMMERCE_MANAGE: "commerce:manage",
    COMMERCE_VIEW: "commerce:view",
    VIEWER: "viewer",
    METRICS_VIEW: "metrics:view",
    ORDERS_VIEW: "orders:view",
    ORDERS_MANAGE: "orders:manage",
    PRODUCTS_VIEW: "products:view",
    PRODUCTS_MANAGE: "products:manage",
    PRODUCTS_EDIT: "products:edit",
    MARKETING_MANAGE: "marketing:manage",
    MARKETING_VIEW: "marketing:view",
    FULFILLMENT_VIEW: "fulfillment:view",
    FULFILLMENT_MANAGE: "fulfillment:manage",
    SUPPORT_VIEW: "support:view",
    SUPPORT_MANAGE: "support:manage",
    CUSTOMERS_VIEW: "customers:view",
    CUSTOMERS_MANAGE: "customers:manage",
};
export const ROLES = {
    OWNER: "owner",
    ADMIN: "admin",
    STAFF: "staff",
    FINANCE: "finance",
    SUPPORT: "support",
    VIEWER: "viewer",
};
const ROLE_PERMISSIONS = {
    [ROLES.OWNER]: ["*"], // wildcard
    [ROLES.ADMIN]: [
        PERMISSIONS.TEAM_MANAGE,
        PERMISSIONS.REFUNDS_MANAGE,
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_EDIT,
        PERMISSIONS.PAYOUTS_MANAGE,
        PERMISSIONS.DOMAINS_MANAGE,
        PERMISSIONS.INTEGRATIONS_MANAGE,
        PERMISSIONS.TEMPLATES_MANAGE,
        PERMISSIONS.KYC_MANAGE,
        PERMISSIONS.BILLING_MANAGE,
        PERMISSIONS.COMMERCE_MANAGE,
        PERMISSIONS.COMMERCE_VIEW,
        PERMISSIONS.METRICS_VIEW,
        PERMISSIONS.ORDERS_VIEW,
        PERMISSIONS.ORDERS_MANAGE,
        PERMISSIONS.PRODUCTS_VIEW,
        PERMISSIONS.PRODUCTS_MANAGE,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_MANAGE,
        PERMISSIONS.SUPPORT_VIEW,
        PERMISSIONS.SUPPORT_MANAGE,
    ],
    [ROLES.STAFF]: [
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.REFUNDS_MANAGE,
        PERMISSIONS.COMMERCE_MANAGE,
        PERMISSIONS.COMMERCE_VIEW,
        PERMISSIONS.ORDERS_VIEW,
        PERMISSIONS.ORDERS_MANAGE,
        PERMISSIONS.PRODUCTS_VIEW,
    ],
    [ROLES.FINANCE]: [
        PERMISSIONS.REFUNDS_MANAGE,
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.PAYOUTS_MANAGE,
        PERMISSIONS.COMMERCE_VIEW,
        PERMISSIONS.ORDERS_VIEW,
        PERMISSIONS.METRICS_VIEW,
        PERMISSIONS.FINANCE_VIEW,
    ],
    [ROLES.SUPPORT]: [
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.REFUNDS_MANAGE,
        PERMISSIONS.COMMERCE_VIEW,
        PERMISSIONS.ORDERS_VIEW,
        PERMISSIONS.ORDERS_MANAGE,
        PERMISSIONS.SUPPORT_VIEW,
        PERMISSIONS.SUPPORT_MANAGE,
    ],
    [ROLES.VIEWER]: [PERMISSIONS.VIEWER, PERMISSIONS.COMMERCE_VIEW, PERMISSIONS.SETTINGS_VIEW],
};
export function can(role, action) {
    const perms = ROLE_PERMISSIONS[role] || [];
    if (perms.includes("*"))
        return true;
    return perms.includes(action);
}
