"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { History, User, RefreshCw } from "lucide-react";
import { useOpsQuery } from "@/hooks/useOpsQuery";
import { Button } from "@vayva/ui";
export default function AuditPage() {
    const { data: logs, isLoading, refetch } = useOpsQuery(["system-audit"], () => fetch("/api/ops/admin/audit").then(res => res.json().then(j => j.data)));
    return (_jsxs("div", { className: "p-8 space-y-6", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { children: [_jsxs("h1", { className: "text-3xl font-bold text-gray-900 flex items-center gap-3", children: [_jsx(History, { className: "w-8 h-8 text-indigo-600" }), "System Audit Log"] }), _jsx("p", { className: "text-gray-500 mt-1", children: "Unified timestamped log of internal administrative actions." })] }), _jsx(Button, { variant: "ghost", size: "icon", onClick: () => refetch(), className: "rounded-full h-8 w-8", "aria-label": "Refresh audit logs", children: _jsx(RefreshCw, { className: `w-5 h-5 text-gray-500 ${isLoading ? 'animate-spin' : ''}` }) })] }), _jsx("div", { className: "bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden", children: _jsxs("table", { className: "w-full text-left text-sm", children: [_jsx("thead", { className: "bg-gray-50 text-gray-500 border-b border-gray-100", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 font-medium", children: "Event" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Actor" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Details" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Time" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-100", children: isLoading ? (_jsx("tr", { children: _jsx("td", { colSpan: 4, className: "p-12 text-center text-gray-400", children: "Loading audit log..." }) })) : !logs?.length ? (_jsx("tr", { children: _jsx("td", { colSpan: 4, className: "p-12 text-center text-gray-400", children: "No activity recorded." }) })) : (logs.map((log) => (_jsxs("tr", { className: "hover:bg-gray-50", children: [_jsx("td", { className: "px-6 py-4 font-mono text-xs text-indigo-700 font-bold", children: log.eventType }), _jsxs("td", { className: "px-6 py-4 flex items-center gap-2", children: [_jsx("span", { className: "bg-gray-100 p-1 rounded-full text-gray-500", children: _jsx(User, { size: 12 }) }), _jsx("span", { className: "font-medium text-gray-900", children: log.OpsUser?.name || "System" })] }), _jsx("td", { className: "px-6 py-4", children: _jsx("pre", { className: "text-[10px] text-gray-500 bg-gray-50 rounded p-1 max-w-xs overflow-x-auto", children: JSON.stringify(log.metadata, null, 0) }) }), _jsx("td", { className: "px-6 py-4 text-gray-500 text-xs", children: new Date(log.createdAt).toLocaleString() })] }, log.id)))) })] }) })] }));
}
