import { PrismaClient, Prisma } from "./generated/client";
// import { PrismaPg } from "@prisma/adapter-pg";
// import pg from "pg";

// Re-export PrismaClient and Prisma


export {
  PrismaClient,
  Prisma,

  // Core Enums from schema.prisma (Verified present in generated client)
  AiActionStatus,
  ApiKeyStatus,
  AppRole,
  ApprovalStatus,
  BillingProvider,
  CampaignChannel,
  CampaignSendStatus,
  CampaignStatus,
  CampaignType,
  Channel,
  ChecklistCategory,
  ChecklistStatus,
  CouponStatus,
  DLQStatus,
  DataRequestStatus,
  DataRequestType,
  DeviceStatus,
  DeviceType,
  Direction,
  DiscountAppliesTo,
  DiscountType,
  DisputeEvidenceType,
  DisputeProvider,
  DisputeStatus,
  EnforcementActionType,
  EnforcementScope,
  EvidenceFileType,
  EvidenceScope,
  FlagSeverity,
  FulfillmentStatus,
  IdempotencyStatus,
  JobRunStatus,
  KycStatus,
  LegalKey,
  ListingStatus,
  MessageStatus,
  MessageType,
  MetricPeriod,
  MigrationStatus,
  OnboardingStatus,
  OrderStatus,
  OutboxEventStatus,
  PaymentStatus,
  PolicyStatus,
  PolicyType,
  ReportEntityType,
  ReportReason,
  ReportStatus,
  RestockAction,
  ReturnCondition,
  ReturnMethod,
  ReturnReason,
  ReturnResolution,
  ReturnStatus,
  ReviewStatus,
  RiskScope,
  RiskSeverity,
  RiskStatus,
  SubscriptionPlan,
  SubscriptionStatus,
  SupportCaseCategory,
  SupportCaseStatus,
  ThemeStatus,
  VirtualAccountStatus,
  WebhookDeliveryStatus,
  WebhookEndpointStatus,
  ExportStatus,
  DataDeletionStatus,
  DeletionStatus,
  MerchantType,
  ImportOrderState,

  // Additional Enums from schema.prisma
  BookingStatus,
  RaffleEntryStatus,
  Transmission,
  FuelType,
  AccommodationType,
  PostStatus,
  AutomationTrigger,
  AutomationAction,
  LedgerAccountType,
  TransactionType,
} from "./generated/client";

// Types are safe to wildcard export as they don't trigger Turbopack re-export warnings
export type * from "./generated/client";
export type {
  AbuseRule,
  AccountDeletionRequest,
  AdminAuditLog,
  AiActionDefinition,
  AiActionMessageLink,
  AiActionRun,
  AiAddonPurchase,
  AiPlan,
  AiTrace,
  AiUsageDaily,
  AiUsageEvent,
  AnalyticsDailyDelivery,
  AnalyticsDailyPayments,
  AnalyticsDailySales,
  AnalyticsDailySupport,
  AnalyticsEvent,
  ApiError,
  ApiKey,
  Approval,
  ApprovalExecutionLog,
  AuditEvent,
  AuditLog,
  AutomationRule,
  LedgerAccount,
  LedgerTransaction,
  BackupReceipt,
  BankBeneficiary,
  BillingProfile,
  Campaign,
  CampaignSend,
  CarrierAccount,
  Charge,
  Collection,
  CollectionProduct,
  Contact,
  Conversation,
  ConversionEvent,
  CostAnomalyEvent,
  Coupon,
  CustomDomain,
  Customer,
  CustomerAccount,
  CustomerAddress,
  CustomerRiskProfile,
  CustomerSession,
  Cart,
  CartItem,

  DataDeletionRequest,
  DataExportArtifact,
  DataExportRequest,
  DataRequest,
  DeadLetterQueue,
  DeliveryEvent,
  DeliveryOption,
  DeliveryProfile,
  DeliveryWebhookEvent,
  DeliveryZone,
  DeviceRegistration,
  DiscountRedemption,
  DiscountRule,
  DispatchJob,
  Dispute,
  DisputeEvidence,
  DisputeSubmission,
  DisputeTimelineEvent,
  DomainMapping,
  DunningAttempt,
  EnforcementAction,
  EvidenceAsset,
  EvidenceBundle,
  ExportJob,
  FeatureFlag,
  FlashSale,
  GoLiveChecklistItem,
  Goal,
  HandoffEvent,
  HealthScore,
  IdempotencyKeyV2,
  FulfillmentGroup,
  ImportJob,
  IntegrationEvent,
  InternalNote,
  InventoryEvent,
  InventoryItem,
  InventoryLocation,
  InventoryMovement,
  InvoiceLineV2,
  InvoiceV2,
  JobRun,
  KnowledgeBaseEntry,
  KnowledgeEmbedding,
  KycRecord,
  LedgerEntry,
  LegalAcceptance,
  LegalTemplate,
  MarketplaceListing,
  MediaAsset,
  Membership,
  MerchantAiProfile,
  MerchantAiSubscription,
  MerchantCostDaily,
  MerchantFeatureOverride,
  MerchantFlag,
  MerchantOnboarding,
  OnboardingAnalyticsEvent,
  MerchantPolicy,
  MerchantSession,
  MerchantTheme,
  MerchantThemeHistory,
  Message,
  MigrationRun,
  Notification,
  NotificationLog,
  NotificationOutbox,
  NotificationPreference,
  NotificationTemplate,
  ObjectionEvent,
  OnboardingFlow,
  OpsAuditEvent,
  OpsSession,
  OpsUser,
  Order,
  OrderDiscount,
  OrderEvent,
  OrderItem,
  OrderTimelineEvent,
  OtpCode,
  OutboxEvent,
  Partner,
  PartnerPayoutLedger,
  PartnerReferralCode,
  PaymentAccount,
  PaymentCustomer,
  PaymentIntent,
  PaymentTransaction,
  PaymentWebhookEvent,
  Payout,
  Permission,
  PersuasionAttempt,
  Plan,
  PlatformCostDaily,
  PlatformKillSwitch,
  PricingTier,
  Product,
  ProductImage,
  ProductVariant,
  ProviderPricing,
  PublishHistory,
  RateLimit,
  Receipt,
  ReferralAttribution,
  Refund,
  Report,
  RescueFixAction,
  RescueIncident,
  ReturnItem,
  ReturnLogistics,
  ReturnRequest,
  Review,
  ReviewMedia,
  RiskProfile,
  RiskSignal,
  Role,
  RolePermission,
  SecuritySetting,
  Segment,
  Shipment,
  SignupAbuseSignal,
  SourcingRequest,
  StaffInvite,
  StatusIncident,
  Store,
  StoreCounter,
  StoreDeliverySettings,
  StoreProfile,
  StoreTemplateSelection,
  StorefrontDraft,
  StorefrontPublished,
  StorefrontSettings,
  Subscription,
  SupportBotFeedback,
  SupportCase,
  SupportSlaPolicy,
  SupportTelemetryEvent,
  SupportTicket,
  TelemetryEvent,
  Template,
  TemplateAsset,
  TemplateManifest,
  TemplateSource,
  TemplateSyncRun,
  TemplateVersion,
  Tenant,
  TenantMembership,
  ThrottlePolicy,
  TicketMessage,
  TrackingEvent,
  TrustBadgeSnapshot,
  UptimeCheck,
  UsageCounter,
  User,
  UserSession,
  Wallet,
  WebhookDelivery,
  WebhookEndpoint,
  WebhookEvent,
  WebhookEventV2,
  WebhookSubscription,

} from "./generated/client";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

// import { PrismaPg } from "@prisma/adapter-pg";
// import pg from "pg";
// const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
// const adapter = new PrismaPg(pool);

export const prisma = globalForPrisma.prisma ?? new PrismaClient(); // Removed { adapter }

export * from "./helpers/idempotency";

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
