"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Users, RefreshCw, Link2 } from "lucide-react";
import { useOpsQuery } from "@/hooks/useOpsQuery";
import { Button } from "@vayva/ui";
export default function PartnersPage() {
    const { data: partners, isLoading, refetch } = useOpsQuery(["partners-list"], () => fetch("/api/ops/partners").then(res => res.json().then(j => j.data)));
    return (_jsxs("div", { className: "p-8 space-y-6", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { children: [_jsxs("h1", { className: "text-3xl font-bold text-gray-900 flex items-center gap-3", children: [_jsx(Users, { className: "w-8 h-8 text-indigo-600" }), "Partner Directory"] }), _jsx("p", { className: "text-gray-500 mt-1", children: "Manage affiliate partners and referrals." })] }), _jsx(Button, { variant: "ghost", size: "icon", onClick: () => refetch(), className: "rounded-full h-8 w-8", "aria-label": "Refresh partners directory", children: _jsx(RefreshCw, { className: `w-5 h-5 text-gray-500 ${isLoading ? 'animate-spin' : ''}` }) })] }), _jsx("div", { className: "bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden", children: _jsxs("table", { className: "w-full text-left text-sm", children: [_jsx("thead", { className: "bg-gray-50 text-gray-500 border-b border-gray-100", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 font-medium", children: "Partner Name" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Type" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Status" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Referrals" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Joined" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-100", children: isLoading ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "p-12 text-center text-gray-400", children: "Loading partners..." }) })) : !partners?.length ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "p-12 text-center text-gray-400", children: "No partners found." }) })) : (partners.map((p) => (_jsxs("tr", { className: "hover:bg-gray-50", children: [_jsx("td", { className: "px-6 py-4 font-medium text-gray-900", children: p.name }), _jsx("td", { className: "px-6 py-4 text-gray-600 uppercase text-xs font-bold", children: p.type }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: `px-2 py-0.5 rounded text-xs font-bold ${p.status === "active" ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-600"}`, children: p.status }) }), _jsxs("td", { className: "px-6 py-4 flex items-center gap-1 font-mono", children: [_jsx(Link2, { size: 12, className: "text-gray-400" }), p._count?.referralAttributions || 0] }), _jsx("td", { className: "px-6 py-4 text-gray-500 text-xs", children: new Date(p.createdAt).toLocaleDateString() })] }, p.id)))) })] }) })] }));
}
