import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Link from "next/link";
const legalDocuments = [
    { title: "Legal Hub", href: "/legal" },
    { title: "Terms of Service", href: "/legal/terms" },
    { title: "Privacy Policy", href: "/legal/privacy" },
    { title: "Acceptable Use Policy", href: "/legal/acceptable-use" },
    { title: "Prohibited Items", href: "/legal/prohibited-items" },
    { title: "Refund Policy", href: "/legal/refund-policy", active: true },
    { title: "KYC & Compliance", href: "/legal/kyc-safety" },
    { title: "Manage Cookies", href: "/legal/cookies" },
];
export default function RefundPolicyPage() {
    return (_jsx("div", { className: "min-h-screen bg-white", children: _jsx("div", { className: "max-w-7xl mx-auto px-6 py-16", children: _jsxs("div", { className: "flex gap-12", children: [_jsx("aside", { className: "w-64 flex-shrink-0", children: _jsxs("nav", { className: "sticky top-24", children: [_jsx("h3", { className: "text-sm font-semibold text-gray-900 mb-4", children: "Legal Documents" }), _jsx("ul", { className: "space-y-2", children: legalDocuments.map((doc) => (_jsx("li", { children: _jsx(Link, { href: doc.href, className: `block px-3 py-2 text-sm rounded ${doc.active
                                                ? "bg-gray-100 text-gray-900 font-medium"
                                                : "text-gray-600 hover:bg-gray-50 hover:text-gray-900"}`, children: doc.title }) }, doc.href))) })] }) }), _jsxs("main", { className: "flex-1 max-w-3xl prose prose-gray", children: [_jsx("h1", { children: "Refund Policy" }), _jsxs("div", { className: "not-prose mb-8 text-sm text-gray-600", children: [_jsxs("p", { children: [_jsx("strong", { children: "Last Updated:" }), " January 1, 2025"] }), _jsxs("p", { children: [_jsx("strong", { children: "Governing Entity:" }), " Vayva Tech (operating in Nigeria)"] })] }), _jsx("h2", { children: "1. Subscription Refunds" }), _jsx("p", { children: "Vayva provides software-as-a-service (SaaS) and follows a no-refund policy for subscription fees. Since we offer a 7-day free trial for new users to evaluate the Service, we do not provide refunds once a paid subscription has been initiated or renewed." }), _jsx("p", { children: "You may cancel your subscription at any time. Upon cancellation, you will continue to have access to the Service until the end of your current billing period. No partial refunds will be issued for unused time." }), _jsx("h2", { children: "2. Transaction & Withdrawal Fees" }), _jsxs("p", { children: [_jsx("strong", { children: "Withdrawal fees (3%) are non-refundable." }), " Once a withdrawal request is processed and the fee is deducted, the fee cannot be refunded or reversed, as it covers the costs associated with the fund settlement and transaction processing."] }), _jsx("h2", { children: "3. Merchant-Customer Disputes" }), _jsx("p", { children: "Vayva is a software provider and does not handle payments between you and your customers directly. Any refunds for goods or services sold by you to your customers must be handled directly between you and the customer. Vayva is not responsible for, and will not facilitate, refunds for merchant-customer transactions." }), _jsx("h2", { children: "4. Exceptions" }), _jsx("p", { children: "We may, at our sole discretion, issue refunds in exceptional circumstances, such as:" }), _jsxs("ul", { children: [_jsx("li", { children: "Technical errors where you were charged multiple times for the same subscription" }), _jsx("li", { children: "Where required by mandatory Nigerian consumer protection laws" })] }), _jsx("h2", { children: "5. Contact Us" }), _jsx("p", { children: "If you believe you are entitled to an exception or have questions about your billing, please contact us at:" }), _jsxs("p", { children: [_jsx("strong", { children: "Vayva Billing Support" }), _jsx("br", {}), "Email: billing@vayva.shop"] })] })] }) }) }));
}
