"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Megaphone, Plus, Send, Eye } from "lucide-react";
import { useOpsQuery } from "@/hooks/useOpsQuery";
import { cn, Button } from "@vayva/ui";
export default function CampaignManagerPage() {
    const [filter, setFilter] = useState("ALL");
    const { data: campaigns, isLoading } = useOpsQuery(["ops-campaigns", filter], () => fetch(`/api/ops/growth/campaigns?status=${filter}`).then(res => res.json().then(j => j.data)));
    return (_jsxs("div", { className: "p-8 space-y-6", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { children: [_jsxs("h1", { className: "text-3xl font-bold text-gray-900 flex items-center gap-3", children: [_jsx(Megaphone, { className: "w-8 h-8 text-indigo-600" }), "Campaign Manager"] }), _jsx("p", { className: "text-gray-500 mt-1", children: "Design and schedule cross-platform customer lifecycle messaging." })] }), _jsxs(Button, { className: "font-bold rounded-lg transition-all flex items-center gap-2 shadow-lg active:scale-95 h-auto", children: [_jsx(Plus, { size: 20 }), " New Campaign"] })] }), _jsx("div", { className: "flex gap-2 border-b border-gray-200 pb-2", children: ["DRAFT", "SCHEDULED", "SENT", "ALL"].map(s => (_jsx(Button, { onClick: () => setFilter(s), variant: "ghost", className: cn("px-4 py-2 text-sm font-bold border-b-2 transition-colors -mb-2 rounded-none hover:bg-transparent h-auto", filter === s ? "border-indigo-600 text-indigo-600" : "border-transparent text-gray-500 hover:text-gray-700"), children: s }, s))) }), _jsx("div", { className: "bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden", children: _jsxs("table", { className: "w-full text-left text-sm", children: [_jsx("thead", { className: "bg-gray-50 text-gray-500 border-b border-gray-100 font-bold", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3", children: "Campaign Name" }), _jsx("th", { className: "px-6 py-3", children: "Channel" }), _jsx("th", { className: "px-6 py-3", children: "Status" }), _jsx("th", { className: "px-6 py-3", children: "Scheduled" }), _jsx("th", { className: "px-6 py-3 text-right", children: "Actions" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-100", children: isLoading ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "p-12 text-center text-gray-400", children: "Loading campaigns..." }) })) : !campaigns?.length ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "p-12 text-center text-gray-400 font-medium", children: "No campaigns found." }) })) : (campaigns.map((c) => (_jsxs("tr", { className: "hover:bg-gray-50/50 transition-colors group", children: [_jsxs("td", { className: "px-6 py-4", children: [_jsx("div", { className: "font-bold text-gray-900", children: c.name }), _jsxs("div", { className: "text-[10px] text-gray-400 font-mono", children: ["#", c.id.slice(0, 8)] })] }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: "text-xs font-bold bg-gray-100 px-2 py-1 rounded text-gray-600 uppercase", children: c.channel }) }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: cn("px-2 py-0.5 rounded text-[10px] font-black uppercase", c.status === "SENT" ? "bg-green-100 text-green-700" :
                                                c.status === "SCHEDULED" ? "bg-blue-100 text-blue-700" :
                                                    "bg-amber-100 text-amber-700"), children: c.status }) }), _jsx("td", { className: "px-6 py-4 text-gray-500 text-xs font-medium", children: c.scheduledAt ? new Date(c.scheduledAt).toLocaleString() : "Manual only" }), _jsx("td", { className: "px-6 py-4 text-right", children: _jsxs("div", { className: "flex justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity", children: [_jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 text-gray-400 hover:text-indigo-600 hover:bg-indigo-50", title: "View Preview", children: _jsx(Eye, { size: 16 }) }), _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8 text-gray-400 hover:text-indigo-600 hover:bg-indigo-50", title: "Send Now", children: _jsx(Send, { size: 16 }) })] }) })] }, c.id)))) })] }) })] }));
}
