import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Download, Search, ShoppingCart, User } from "lucide-react";
import Link from "next/link";
import { useStore } from "@/context/StoreContext";
import { Button } from "@vayva/ui";
export const DigitalHeader = ({ storeName = "CREATOR HUB", }) => {
    const { cart } = useStore();
    const cartCount = cart.reduce((acc, item) => acc + item.quantity, 0);
    return (_jsx("header", { className: "sticky top-0 z-50 bg-[#0B0F19] border-b border-gray-800 text-gray-100", children: _jsxs("div", { className: "max-w-6xl mx-auto px-6 h-20 flex items-center justify-between", children: [_jsxs(Link, { href: "/", className: "flex items-center gap-2 group", children: [_jsx("div", { className: "w-8 h-8 bg-indigo-500 rounded flex items-center justify-center text-white", children: _jsx(Download, { size: 18, strokeWidth: 3 }) }), _jsx("span", { className: "font-bold text-xl tracking-tight group-hover:text-white transition-colors", children: storeName })] }), _jsxs("nav", { className: "hidden md:flex items-center gap-8 text-sm font-medium text-gray-400", children: [_jsx(Link, { href: "#", className: "hover:text-indigo-400 transition-colors", children: "Templates" }), _jsx(Link, { href: "#", className: "hover:text-indigo-400 transition-colors", children: "UI Kits" }), _jsx(Link, { href: "#", className: "hover:text-indigo-400 transition-colors", children: "E-books" })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx(Button, { variant: "ghost", size: "icon", className: "p-2 hover:bg-gray-800 rounded-full text-gray-400 hover:text-white transition-colors h-auto", "aria-label": "Search", children: _jsx(Search, { size: 20 }) }), _jsxs(Link, { href: "/cart", className: "p-2 hover:bg-gray-800 rounded-full text-gray-400 hover:text-white transition-colors relative", children: [_jsx(ShoppingCart, { size: 20 }), cartCount > 0 && (_jsx("span", { className: "absolute top-1 right-1 h-2 w-2 bg-indigo-500 rounded-full" }))] }), _jsxs(Button, { variant: "ghost", className: "hidden sm:flex items-center gap-2 bg-gray-800 hover:bg-gray-700 px-4 py-2 rounded-lg text-sm font-medium transition-colors ml-2 h-auto", "aria-label": "Sign in", children: [_jsx(User, { size: 16 }), _jsx("span", { children: "Sign In" })] })] })] }) }));
};
