"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import Link from "next/link";
import { StoreShell } from "@/components/storefront/store-shell";
import { Button, Icon } from "@vayva/ui";
export default function OrderConfirmationPage({ params, }) {
    const { slug } = React.use(params);
    return (_jsx(StoreShell, { slug: slug, children: _jsxs("div", { className: "max-w-3xl mx-auto px-4 py-16 text-center", children: [_jsx("div", { className: "w-20 h-20 bg-state-success rounded-full flex items-center justify-center text-black mx-auto mb-6", children: _jsx(Icon, { name: "Check", size: 40 }) }), _jsx("h1", { className: "text-3xl font-bold text-white mb-2", children: "Order Confirmed!" }), _jsxs("p", { className: "text-text-secondary mb-8", children: ["Thank you for shopping with us. Your order", " ", _jsx("span", { className: "text-white font-mono", children: "#VV-90123" }), " has been received."] }), _jsxs("div", { className: "bg-white/5 rounded-2xl border border-white/5 p-6 mb-8 text-left", children: [_jsx("h3", { className: "font-bold text-white mb-4 border-b border-white/5 pb-2", children: "Order Details" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6 text-sm", children: [_jsxs("div", { children: [_jsx("div", { className: "text-text-secondary mb-1", children: "Contact" }), _jsx("div", { className: "text-white", children: "chidinma@example.com" }), _jsx("div", { className: "text-white", children: "+234 812 345 6789" })] }), _jsxs("div", { children: [_jsx("div", { className: "text-text-secondary mb-1", children: "Shipping Address" }), _jsx("div", { className: "text-white", children: "12 Lekki Phase 1" }), _jsx("div", { className: "text-white", children: "Lagos, Nigeria" })] }), _jsxs("div", { children: [_jsx("div", { className: "text-text-secondary mb-1", children: "Payment Method" }), _jsxs("div", { className: "text-white flex items-center gap-2", children: [_jsx(Icon, { name: "CreditCard", size: 14 }), " Ending in 4242"] })] }), _jsxs("div", { children: [_jsx("div", { className: "text-text-secondary mb-1", children: "Expected Delivery" }), _jsx("div", { className: "text-state-success font-bold", children: "Tomorrow, 12PM - 4PM" })] })] })] }), _jsxs("div", { className: "flex gap-4 justify-center", children: [_jsx(Link, { href: `/store/${slug}/track`, children: _jsx(Button, { variant: "outline", className: "border-white/10 text-white hover:bg-white/5", children: "Track Order" }) }), _jsx(Link, { href: `/store/${slug}/collections/all`, children: _jsx(Button, { className: "bg-primary text-black hover:bg-primary/90", children: "Continue Shopping" }) })] }), _jsxs("div", { className: "mt-12 p-4 bg-emerald-500/10 rounded-xl border border-emerald-500/20 max-w-lg mx-auto", children: [_jsxs("div", { className: "flex items-center gap-3 justify-center mb-2", children: [_jsx(Icon, { name: "MessageCircle", className: "text-emerald-400" }), _jsx("span", { className: "font-bold text-emerald-400", children: "Need updates?" })] }), _jsx("p", { className: "text-emerald-200/70 text-sm mb-3", children: "Get real-time delivery updates on WhatsApp." }), _jsx(Button, { size: "sm", className: "bg-emerald-600 text-white hover:bg-emerald-500 border-none rounded-full", children: "Enable WhatsApp Updates" })] })] }) }));
}
