import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CustomerStatus } from "@vayva/shared";
import { Icon } from "@vayva/ui";
export const CustomerOverview = ({ customers }) => {
    const total = customers.length;
    const returning = customers.filter((c) => c.status === CustomerStatus.RETURNING || c.status === CustomerStatus.VIP).length;
    const newCustomers = customers.filter((c) => c.status === CustomerStatus.NEW).length;
    // Test sort by spend for 'Top'
    const topCustomer = [...customers].sort((a, b) => b.totalSpend - a.totalSpend)[0];
    return (_jsxs("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-4 mb-8", children: [_jsxs("div", { className: "bg-white border border-gray-200 rounded-xl p-4 flex items-center gap-3 shadow-sm hover:shadow-md transition-shadow", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-blue-50 flex items-center justify-center text-blue-600", children: _jsx(Icon, { name: "Users", size: 20 }) }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-500", children: "Total Customers" }), _jsx("p", { className: "font-bold text-lg text-gray-900", children: total })] })] }), _jsxs("div", { className: "bg-white border border-gray-200 rounded-xl p-4 flex items-center gap-3 shadow-sm hover:shadow-md transition-shadow", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-green-50 flex items-center justify-center text-green-600", children: _jsx(Icon, { name: "Repeat", size: 20 }) }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-500", children: "Repeat Customers" }), _jsx("p", { className: "font-bold text-lg text-gray-900", children: returning })] })] }), _jsxs("div", { className: "bg-white border border-gray-200 rounded-xl p-4 flex items-center gap-3 shadow-sm hover:shadow-md transition-shadow", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-purple-50 flex items-center justify-center text-purple-600", children: _jsx(Icon, { name: "UserPlus", size: 20 }) }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-500", children: "New this week" }), _jsx("p", { className: "font-bold text-lg text-gray-900", children: newCustomers })] })] }), topCustomer && (_jsxs("div", { className: "bg-white border border-gray-200 rounded-xl p-4 flex items-center gap-3 shadow-sm hover:shadow-md transition-shadow cursor-pointer", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-amber-50 flex items-center justify-center text-amber-600", children: _jsx(Icon, { name: "Crown", size: 20 }) }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-500", children: "Top Customer" }), _jsx("p", { className: "font-bold text-sm text-gray-900 truncate max-w-[120px]", children: topCustomer.name })] })] }))] }));
};
