import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@vayva/ui"; // Assuming generic UI
export default function EditorialHome({ store }) {
    // Mock Data
    const posts = [
        { id: 1, title: "The Future of Minimalist Design", excerpt: "Less is more. Discover how 2024 is shaping up to be the year of reduction.", image: "/images/blog-1.jpg" },
        { id: 2, title: "Curating Your Workspace", excerpt: "A guide to selecting the perfect tools for productivity.", image: "/images/blog-2.jpg" },
        { id: 3, title: "Sustainable Materials in Tech", excerpt: "Why aluminum and glass are making a comeback.", image: "/images/blog-3.jpg" },
    ];
    return (_jsxs("div", { className: "bg-white min-h-screen font-serif text-gray-900", children: [_jsxs("header", { className: "py-8 border-b text-center", children: [_jsx("h1", { className: "text-4xl font-bold tracking-tighter uppercase", children: store.name || " The Daily Edit" }), _jsxs("nav", { className: "mt-4 space-x-6 text-sm font-medium uppercase text-gray-500", children: [_jsx("a", { href: "#", className: "hover:text-black", children: "Culture" }), _jsx("a", { href: "#", className: "hover:text-black", children: "Design" }), _jsx("a", { href: "#", className: "hover:text-black", children: "Technology" }), _jsx("a", { href: "#", className: "hover:text-black", children: "Shop" })] })] }), _jsxs("section", { className: "max-w-6xl mx-auto px-6 py-12 grid grid-cols-1 md:grid-cols-2 gap-12 items-center", children: [_jsx("div", { className: "aspect-[4/3] bg-gray-200" }), _jsxs("div", { children: [_jsx("span", { className: "text-xs font-bold uppercase tracking-widest text-gray-400", children: "Featured Story" }), _jsx("h2", { className: "text-5xl font-medium mt-4 mb-6 leading-tight", children: "The Art of Slow Living in a Fast World." }), _jsx("p", { className: "text-xl text-gray-500 mb-8", children: "We explore how modern creatives are finding balance through intentional design." }), _jsx(Button, { variant: "outline", className: "border-black text-black hover:bg-black hover:text-white rounded-none px-8 h-auto", "aria-label": "Read story", children: "Read Story" })] })] }), _jsx("hr", { className: "mb-16" }), _jsx("section", { className: "max-w-6xl mx-auto px-6 pb-24", children: _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-x-8 gap-y-16", children: posts.map(post => (_jsxs("div", { className: "group cursor-pointer", children: [_jsx("div", { className: "aspect-[3/4] bg-gray-100 mb-6 group-hover:opacity-90 transition-opacity" }), _jsx("h3", { className: "text-2xl font-medium mb-3 group-hover:underline", children: post.title }), _jsx("p", { className: "text-gray-500 leading-relaxed is-truncated", children: post.excerpt })] }, post.id))) }) })] }));
}
