"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { MessageSquare, Mail, Smartphone, RefreshCw } from "lucide-react";
import { useOpsQuery } from "@/hooks/useOpsQuery";
import { Button } from "@vayva/ui";
export default function CommunicationsPage() {
    const [filter, setFilter] = useState("ALL");
    const { data: logs, isLoading, refetch } = useOpsQuery(["comm-logs", filter], () => fetch(`/api/ops/communications/logs?status=${filter}`).then(res => res.json().then(j => j.data)));
    const getChannelIcon = (channel) => {
        if (channel === "EMAIL")
            return _jsx(Mail, { size: 14, className: "text-blue-500" });
        if (channel === "SMS")
            return _jsx(Smartphone, { size: 14, className: "text-purple-500" });
        return _jsx(MessageSquare, { size: 14 });
    };
    return (_jsxs("div", { className: "p-8 space-y-6", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { children: [_jsxs("h1", { className: "text-3xl font-bold text-gray-900 flex items-center gap-3", children: [_jsx(MessageSquare, { className: "w-8 h-8 text-indigo-600" }), "Communications Center"] }), _jsx("p", { className: "text-gray-500 mt-1", children: "Audit trail of all outbound notifications." })] }), _jsx(Button, { variant: "ghost", size: "icon", onClick: () => refetch(), className: "rounded-full h-8 w-8", "aria-label": "Refresh communication logs", children: _jsx(RefreshCw, { className: `w-5 h-5 text-gray-500 ${isLoading ? 'animate-spin' : ''}` }) })] }), _jsx("div", { className: "flex gap-2 border-b border-gray-200 pb-2", children: ["ALL", "SENT", "FAILED", "PENDING"].map(s => (_jsx(Button, { variant: filter === s ? "secondary" : "ghost", onClick: () => setFilter(s), className: `px-3 py-1.5 text-xs font-bold rounded-lg transition-colors h-auto ${filter === s ? "bg-indigo-100 text-indigo-700 hover:bg-indigo-200" : "text-gray-600 hover:bg-gray-50"}`, "aria-label": `Filter logs by status: ${s.toLowerCase()}`, children: s }, s))) }), _jsx("div", { className: "bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden", children: _jsxs("table", { className: "w-full text-left text-sm", children: [_jsx("thead", { className: "bg-gray-50 text-gray-500 border-b border-gray-100", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 font-medium", children: "Recipient" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Channel" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Template" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Status" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Time" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-100", children: isLoading ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "p-12 text-center text-gray-400", children: "Loading logs..." }) })) : !logs?.length ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "p-12 text-center text-gray-400", children: "No logs found." }) })) : (logs.map((log) => (_jsxs("tr", { className: "hover:bg-gray-50", children: [_jsx("td", { className: "px-6 py-4 font-mono text-xs text-gray-600", children: log.metadata?.to || log.metadata?.email || "N/A" }), _jsxs("td", { className: "px-6 py-4 flex items-center gap-2", children: [getChannelIcon(log.channel), _jsx("span", { className: "text-xs font-medium", children: log.channel })] }), _jsx("td", { className: "px-6 py-4 text-gray-600", children: log.type }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: `px-2 py-0.5 rounded text-[10px] font-bold ${log.status === "SENT" ? "bg-green-100 text-green-700" :
                                                log.status === "FAILED" ? "bg-red-100 text-red-700" : "bg-yellow-100 text-yellow-700"}`, children: log.status }) }), _jsx("td", { className: "px-6 py-4 text-gray-500 text-xs", children: new Date(log.createdAt).toLocaleString() })] }, log.id)))) })] }) })] }));
}
