// Deprecated for backward compat if needed, but we prefer checking IndustrySlug
export var TemplateCategory;
(function (TemplateCategory) {
    TemplateCategory["RETAIL"] = "Retail";
    TemplateCategory["SERVICE"] = "Service";
    TemplateCategory["FOOD"] = "Food";
    TemplateCategory["DIGITAL"] = "Digital";
    TemplateCategory["EVENTS"] = "Events";
    TemplateCategory["EDUCATION"] = "Education";
    TemplateCategory["B2B"] = "B2B";
    TemplateCategory["MARKETPLACE"] = "Marketplace";
    TemplateCategory["NONPROFIT"] = "Nonprofit";
    TemplateCategory["REAL_ESTATE"] = "Real Estate";
    TemplateCategory["CREATIVE"] = "Creative & Portfolio";
    TemplateCategory["AUTOMOTIVE"] = "Automotive";
    TemplateCategory["TRAVEL"] = "Travel & Hospitality";
    TemplateCategory["BLOG"] = "Blog & Media";
})(TemplateCategory || (TemplateCategory = {}));
export const TEMPLATE_REGISTRY = {
    "vayva-standard": {
        templateId: "vayva-standard",
        slug: "demo",
        displayName: "Standard Retail",
        category: "Retail",
        industry: "retail",
        businessModel: "Retail",
        primaryUseCase: "General Physical Goods",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "The essential store for physical products.",
            bullets: [
                "Classic hero banner with CTA",
                "Clean collection grid layout",
                "Simple product details page",
            ],
            bestFor: ["Clothing boutiques", "General merchandise", "Pop-up shops"],
            keyModules: ["Product Catalog", "Cart & Checkout", "Order Management"],
        },
        routes: ["/", "/collections/*", "/products/:slug"],
        layoutKey: "StandardRetailHome",
        onboardingProfile: {
            prefill: {
                industryCategory: "retail",
                deliveryEnabled: true,
                paymentsEnabled: true,
            },
            requireSteps: ["finance"],
        },
    },
    "vayva-aa-fashion": {
        templateId: "vayva-aa-fashion",
        slug: "aa-fashion-demo",
        displayName: "A&A Fashion",
        category: "Retail",
        industry: "fashion",
        businessModel: "Retail",
        primaryUseCase: "Fashion / Apparel",
        requiredPlan: "free",
        defaultTheme: "dark",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Bold, visual-first fashion retail.",
            bullets: [
                "Full-width imagery focused",
                "Lookbook style collections",
                "Size guide modal integration",
            ],
            bestFor: ["Fashion brands", "Streetwear", "Luxury apparel"],
            keyModules: ["Visual Merchandising", "Size Variants", "Instagram Feed"],
        },
        routes: ["/", "/collections/*", "/products/:slug"],
        layoutKey: "AAFashionHome",
        componentProps: {
            heroText: "DARK\nMATTER",
            heroSubtext: "Season 04 / 24"
        },
        onboardingProfile: {
            prefill: {
                industryCategory: "fashion",
                deliveryEnabled: true,
                paymentsEnabled: true,
            },
            requireSteps: ["finance"],
        },
    },
    "vayva-gizmo-tech": {
        templateId: "vayva-gizmo-tech",
        slug: "gizmo-demo",
        displayName: "Gizmo Tech",
        category: "Retail",
        industry: "electronics",
        businessModel: "Retail",
        primaryUseCase: "Electronics",
        requiredPlan: "free",
        defaultTheme: "dark",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "High-spec showcase for electronics.",
            bullets: [
                "Spec comparison tables",
                "Dark mode technical aesthetic",
                "Feature highlight grids",
            ],
            bestFor: ["Gadget stores", "Computer shops", "Audio equipment"],
            keyModules: ["Tech Specs", "Product Comparison", "Warranty Info"],
        },
        routes: ["/", "/collections/*", "/products/:slug"],
        layoutKey: "GizmoTechHome",
        onboardingProfile: {
            prefill: {
                industryCategory: "electronics",
                deliveryEnabled: true,
                paymentsEnabled: true,
            },
            requireSteps: ["finance"],
        },
    },
    "vayva-bloome-home": {
        templateId: "vayva-bloome-home",
        slug: "bloome-demo",
        displayName: "Bloome & Home",
        category: "Retail",
        industry: "beauty",
        businessModel: "Retail",
        primaryUseCase: "Home & Lifestyle",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Serene design for lifestyle and beauty.",
            bullets: [
                "Editorial style storytelling",
                "Soft typography and palettes",
                "Ritual/Routine builder layouts",
            ],
            bestFor: ["Home decor", "Skincare/Beauty", "Wellness brands"],
            keyModules: [
                "Subscription Support",
                "Bundle Builder",
                "Blog Integration",
            ],
        },
        routes: ["/", "/collections/*", "/products/:slug"],
        layoutKey: "BloomeHome",
        onboardingProfile: {
            prefill: {
                industryCategory: "beauty",
                deliveryEnabled: true,
                paymentsEnabled: true,
            },
            requireSteps: ["finance"],
        },
    },
    "vayva-bookly-pro": {
        templateId: "vayva-bookly-pro",
        slug: "bookly-demo",
        displayName: "Bookly Pro",
        category: "Service",
        industry: "services",
        businessModel: "Service",
        primaryUseCase: "Appointments / Bookings",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Professional booking system for experts.",
            bullets: [
                "Real-time calendar availability",
                "Service menu with duration",
                "Deposit requirement handling",
            ],
            bestFor: ["Consultants", "Salons & Spas", "Clinics"],
            keyModules: ["Appointment Scheduling", "Staff Management", "Deposits"],
        },
        routes: ["/", "/book/:serviceId"],
        layoutKey: "StandardServiceHome",
        onboardingProfile: {
            prefill: {
                industryCategory: "services",
                deliveryEnabled: false,
                paymentsEnabled: true,
            },
            skipSteps: ["logistics"],
            requireSteps: ["finance"],
        },
    },
    "vayva-chopnow": {
        templateId: "vayva-chopnow",
        slug: "chopnow-demo",
        displayName: "ChopNow",
        category: "Food",
        industry: "food",
        businessModel: "Food",
        primaryUseCase: "Food Delivery / Restaurants",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Fast menu ordering for restaurants.",
            bullets: [
                "Modifier groups (sides, toppings)",
                "Delivery vs Pickup toggle",
                "Visual menu categories",
            ],
            bestFor: ["Restaurants", "Fast Food", "Cloud Kitchens"],
            keyModules: [
                "Kitchen Display System",
                "Menu Modifiers",
                "Delivery Zones",
            ],
        },
        routes: ["/"],
        layoutKey: "QuickBitesFood",
        onboardingProfile: {
            prefill: {
                industryCategory: "food",
                deliveryEnabled: true,
                paymentsEnabled: true,
            },
            requireSteps: ["logistics", "finance"],
        },
    },
    "vayva-file-vault": {
        templateId: "vayva-file-vault",
        slug: "filevault-demo",
        displayName: "FileVault",
        category: "Digital",
        industry: "digital",
        businessModel: "Digital",
        primaryUseCase: "Digital Downloads",
        requiredPlan: "free",
        defaultTheme: "dark",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Secure delivery for digital assets.",
            bullets: [
                "Instant secure download links",
                "License key distribution",
                "Preview for audio/video/pdf",
            ],
            bestFor: ["E-book authors", "Software devs", "Digital artists"],
            keyModules: [
                "Digital Rights Management",
                "Secure Links",
                "Automated Email",
            ],
        },
        routes: ["/"],
        layoutKey: "StandardDigitalHome",
        onboardingProfile: {
            prefill: {
                industryCategory: "digital",
                deliveryEnabled: false,
                paymentsEnabled: true,
            },
            skipSteps: ["logistics"],
            requireSteps: ["finance"],
        },
    },
    "vayva-ticketly": {
        templateId: "vayva-ticketly",
        slug: "ticketly-demo",
        displayName: "Ticketly",
        category: "Events",
        industry: "events",
        businessModel: "Events",
        primaryUseCase: "Ticketing / RSVPs",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Event ticketing and guest management.",
            bullets: [
                "Tiered ticket types (VIP, Early Bird)",
                "Event schedule display",
                "QR code generation",
            ],
            bestFor: ["Concerts", "Workshops", "Conferences"],
            keyModules: ["Ticketing Engine", "QR Check-in", "Guest Lists"],
        },
        routes: ["/", "/events/:slug"],
        layoutKey: "StandardEventsHome",
        onboardingProfile: {
            prefill: {
                industryCategory: "events",
                deliveryEnabled: false,
                paymentsEnabled: true,
            },
            skipSteps: ["logistics"],
            requireSteps: ["finance"],
        },
    },
    "vayva-eduflow": {
        templateId: "vayva-eduflow",
        slug: "eduflow-demo",
        displayName: "Eduflow",
        category: "Education",
        industry: "services", // Fallback from education
        businessModel: "Courses",
        primaryUseCase: "Online Courses / LMS",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Complete Learning Management System.",
            bullets: [
                "Course curriculum outline",
                "Video lesson player",
                "Progress tracking",
            ],
            bestFor: ["Educators", "Coaches", "Training Centers"],
            keyModules: ["LMS Player", "Student Progress", "Quizzes"],
        },
        routes: ["/", "/learn/:courseId"],
        layoutKey: "SkillAcademyCourses",
        onboardingProfile: {
            prefill: {
                industryCategory: "education",
                deliveryEnabled: false,
                paymentsEnabled: true,
            },
            skipSteps: ["logistics"],
            requireSteps: ["finance"],
        },
    },
    "vayva-bulktrade": {
        templateId: "vayva-bulktrade",
        slug: "bulktrade-demo",
        displayName: "BulkTrade",
        category: "B2B",
        industry: "b2b",
        businessModel: "Wholesale",
        primaryUseCase: "Wholesale / Bulk Orders",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "B2B portal for high-volume trade.",
            bullets: [
                "Minimum Order Quantity (MOQ) rules",
                "Tiered volume pricing tables",
                "Request for Quote (RFQ) flow",
            ],
            bestFor: ["Wholesalers", "Manufacturers", "Distributors"],
            keyModules: ["RFQ System", "Volume Pricing", "Invoice Generation"],
        },
        routes: ["/"],
        layoutKey: "BulkTradeHome",
        onboardingProfile: {
            prefill: {
                industryCategory: "b2b",
                deliveryEnabled: true,
                paymentsEnabled: true,
            },
            requireSteps: ["finance", "kyc"],
        },
    },
    "vayva-markethub": {
        templateId: "vayva-markethub",
        slug: "markethub-demo",
        displayName: "MarketHub",
        category: "Marketplace",
        industry: "retail", // Fallback from marketplace
        businessModel: "Marketplace",
        primaryUseCase: "Multi-vendor",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Launch your own multi-vendor platform.",
            bullets: [
                "Vendor profiles and catalogs",
                "Unified cart from multiple sellers",
                "Vendor rating system",
                "Commission engine"
            ],
            bestFor: ["Niche marketplaces", "Aggregators", "Malls"],
            keyModules: [
                "Multi-vendor Payouts",
                "Vendor Portal",
                "Commission Engine",
            ],
        },
        routes: ["/"],
        layoutKey: "CreativeMarketStore",
        onboardingProfile: {
            prefill: {
                industryCategory: "marketplace",
                deliveryEnabled: true,
                paymentsEnabled: true,
            },
            requireSteps: ["finance", "kyc"],
        },
    },
    "vayva-giveflow": {
        templateId: "vayva-giveflow",
        slug: "giveflow-demo",
        displayName: "GiveFlow",
        category: "Nonprofit",
        industry: "nonprofit",
        businessModel: "Donations",
        primaryUseCase: "Fundraising / Charity",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Drive impact with donation campaigns.",
            bullets: [
                "Fundraising goal progress bars",
                "Recurring donation options",
                "Donor wall recognition",
            ],
            bestFor: ["Non-profits", "Charities", "Personal Causes"],
            keyModules: ["Donations", "Recurring Billing", "Goal Tracking"],
        },
        routes: ["/"],
        layoutKey: "GiveFlowHome",
        onboardingProfile: {
            prefill: {
                industryCategory: "nonprofit",
                deliveryEnabled: false,
                paymentsEnabled: true,
            },
            skipSteps: ["logistics"],
            requireSteps: ["finance"],
        },
    },
    "vayva-homelist": {
        templateId: "vayva-homelist",
        slug: "homelist-demo",
        displayName: "HomeList",
        category: "Real Estate",
        industry: "real_estate", // Corrected slug format
        businessModel: "Property",
        primaryUseCase: "Listings / Rentals",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Showcase properties and capture leads.",
            bullets: [
                "Property search with advanced filters",
                "Map integration for locations",
                "Booking viewing appointments",
            ],
            bestFor: ["Real Estate Agents", "Property Managers", "Rental Listings"],
            keyModules: ["Property Listings", "Map View", "Lead Capture Form"],
        },
        routes: ["/", "/properties/*"],
        layoutKey: "HomeListHome",
        onboardingProfile: {
            prefill: {
                industryCategory: "real_estate",
                deliveryEnabled: false,
                paymentsEnabled: false,
            },
            skipSteps: ["logistics", "finance"],
        },
    },
    "vayva-oneproduct": {
        templateId: "vayva-oneproduct",
        slug: "oneproduct-demo",
        displayName: "OneProduct Pro",
        category: "Retail",
        industry: "retail",
        businessModel: "Single Product",
        primaryUseCase: "Funnel / Landing Page",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "High-conversion single product funnel.",
            bullets: [
                "Long-form persuasion layout",
                "Sticky 'Buy Now' mobile CTA",
                "integrated upsell flows",
            ],
            bestFor: ["Dropshippers", "Inventors", "Flash Sales"],
            keyModules: ["Funnel Builder", "Upsells", "Reviews/Social Proof"],
        },
        routes: ["/"],
        layoutKey: "OneProductHome",
        onboardingProfile: {
            prefill: {
                industryCategory: "retail",
                deliveryEnabled: true,
                paymentsEnabled: true,
            },
            requireSteps: ["finance"],
        },
    },
    "slice-life-pizza": {
        templateId: "slice-life-pizza",
        slug: "slice-life",
        displayName: "Slice Life Pizza",
        category: "Food",
        industry: "food",
        businessModel: "Food",
        primaryUseCase: "Pizzerias",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        demoStoreUrl: "/demos/slice-life",
        compare: {
            headline: "Artisanal pizza experience.",
            bullets: [
                "Visual menu with modifiers",
                "Delivery zone checker",
                "Combo builder",
            ],
            bestFor: ["Pizzerias", "Italian Restaurants"],
            keyModules: ["Menu Builder", "Modifiers", "Delivery"],
        },
        routes: ["/"],
        layoutKey: "SliceLifePizza",
        onboardingProfile: {
            prefill: {
                industryCategory: "food",
                deliveryEnabled: true,
                paymentsEnabled: true,
            },
            requireSteps: ["logistics", "finance"],
        },
    },
    "vayva-sneaker-drop": {
        templateId: "vayva-sneaker-drop",
        slug: "sneaker-demo",
        displayName: "Sneaker Drop",
        category: "Retail",
        industry: "fashion",
        businessModel: "Retail",
        primaryUseCase: "Streetwear / Shoes",
        requiredPlan: "free",
        defaultTheme: "dark",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Hype drops and limited editions.",
            bullets: ["Countdown timer", "Raffle system", "High-res gallery"],
            bestFor: ["Sneakerheads", "Streetwear Brands"],
            keyModules: ["Drop Timer", "Waitlist", "Stock Limits"],
        },
        routes: ["/"],
        layoutKey: "AAFashionHome",
        componentProps: {
            heroText: "SNEAKER\nDROP",
            heroSubtext: "Limited Release",
            showTimer: true,
            timerDate: "2025-12-31T00:00:00Z"
        },
        onboardingProfile: { prefill: { industryCategory: "fashion" } },
    },
    "vayva-kids-world": {
        templateId: "vayva-kids-world",
        slug: "kids-demo",
        displayName: "Kids World",
        category: "Retail",
        industry: "retail",
        businessModel: "Retail",
        primaryUseCase: "Toys / Clothing",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Fun and playful store for kids.",
            bullets: ["Bright colors", "Age filters", "Gift bundles"],
            bestFor: ["Toy Stores", "Baby Clothes"],
            keyModules: ["Gift Registry", "Age Filter"],
        },
        routes: ["/"],
        layoutKey: "StandardRetailHome",
        onboardingProfile: { prefill: { industryCategory: "retail" } },
    },
    "vayva-pet-palace": {
        templateId: "vayva-pet-palace",
        slug: "pet-demo",
        displayName: "Pet Palace",
        category: "Retail",
        industry: "retail",
        businessModel: "Retail",
        primaryUseCase: "Pet Supplies",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Where pets are royalty.",
            bullets: ["Subscription treats", "Breed guide", "Vet advice blog"],
            bestFor: ["Pet Shops", "Groomers"],
            keyModules: ["Subscriptions", "Blog"],
        },
        routes: ["/"],
        layoutKey: "StandardRetailHome",
        onboardingProfile: { prefill: { industryCategory: "retail" } },
    },
    "vayva-beauty-box": {
        templateId: "vayva-beauty-box",
        slug: "beauty-demo",
        displayName: "Beauty Box",
        category: "Retail",
        industry: "beauty",
        businessModel: "Retail",
        primaryUseCase: "Subscription Box",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Curated beauty delivered monthly.",
            bullets: ["Quiz funnel", "Monthly themes", "Unboxing experience"],
            bestFor: ["Subscription Boxes", "Cosmetics"],
            keyModules: ["Quiz", "Recurring Billing"],
        },
        routes: ["/"],
        layoutKey: "BloomeHome",
        onboardingProfile: { prefill: { industryCategory: "beauty" } },
    },
    "vayva-active-gear": {
        templateId: "vayva-active-gear",
        slug: "active-demo",
        displayName: "Active Gear",
        category: "Retail",
        industry: "retail",
        businessModel: "Retail",
        primaryUseCase: "Sports / Outdoors",
        requiredPlan: "free",
        defaultTheme: "dark",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Performance gear for athletes.",
            bullets: ["Tech specs", "Activity filter", "Team orders"],
            bestFor: ["Sports Shops", "Outdoor Gear"],
            keyModules: ["Filters", "Bulk Orders"],
        },
        routes: ["/"],
        layoutKey: "GizmoTechHome",
        onboardingProfile: { prefill: { industryCategory: "retail" } },
    },
    "vayva-coffee-house": {
        templateId: "vayva-coffee-house",
        slug: "coffee-demo",
        displayName: "Coffee House",
        category: "Food",
        industry: "food",
        businessModel: "Food",
        primaryUseCase: "Cafe / Coffee Shop",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Order ahead for morning brew.",
            bullets: ["Custom drink builder", "Pickup scheduling", "Loyalty points"],
            bestFor: ["Cafes", "Roasters"],
            keyModules: ["Modifiers", "Loyalty"],
        },
        routes: ["/"],
        layoutKey: "QuickBitesFood",
        onboardingProfile: { prefill: { industryCategory: "food" } },
    },
    "vayva-burger-joint": {
        templateId: "vayva-burger-joint",
        slug: "burger-demo",
        displayName: "Burger Joint",
        category: "Food",
        industry: "food",
        businessModel: "Food",
        primaryUseCase: "Fast Food",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Juicy burgers, fast delivery.",
            bullets: ["Combo deals", "Topping selectors", "Fast checkout"],
            bestFor: ["Burger Shops", "Food Trucks"],
            keyModules: ["Combos", "Delivery"],
        },
        routes: ["/"],
        layoutKey: "QuickBitesFood",
        onboardingProfile: { prefill: { industryCategory: "food" } },
    },
    "vayva-sushi-bar": {
        templateId: "vayva-sushi-bar",
        slug: "sushi-demo",
        displayName: "Sushi Bar",
        category: "Food",
        industry: "food",
        businessModel: "Food",
        primaryUseCase: "Asian Cuisine",
        requiredPlan: "free",
        defaultTheme: "dark",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Elegant dining experience.",
            bullets: ["Omakase menu", "Reservation booking", "Visual gallery"],
            bestFor: ["Sushi", "Fine Dining"],
            keyModules: ["Reservations", "Menu Gallery"],
        },
        routes: ["/"],
        layoutKey: "StandardFoodHome",
        onboardingProfile: { prefill: { industryCategory: "food" } },
    },
    "vayva-bakery": {
        templateId: "vayva-bakery",
        slug: "bakery-demo",
        displayName: "Sweet Bakery",
        category: "Food",
        industry: "food",
        businessModel: "Food",
        primaryUseCase: "Bakery / Sweets",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Fresh pastries daily.",
            bullets: ["Cake customization", "Pre-order for events", "Gift boxes"],
            bestFor: ["Bakeries", "Patisseries"],
            keyModules: ["Custom Orders", "Scheduling"],
        },
        routes: ["/"],
        layoutKey: "StandardFoodHome",
        onboardingProfile: { prefill: { industryCategory: "food" } },
    },
    "vayva-gym-flow": {
        templateId: "vayva-gym-flow",
        slug: "gym-demo",
        displayName: "Gym Flow",
        category: "Service",
        industry: "services",
        businessModel: "Service",
        primaryUseCase: "Fitness / Gym",
        requiredPlan: "free",
        defaultTheme: "dark",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Class bookings and memberships.",
            bullets: ["Class calendar", "Membership plans", "Trainer profiles"],
            bestFor: ["Gyms", "Yoga Studios"],
            keyModules: ["Calendar", "Memberships"],
        },
        routes: ["/"],
        layoutKey: "StandardServiceHome",
        onboardingProfile: { prefill: { industryCategory: "services" } },
    },
    "vayva-law-firm": {
        templateId: "vayva-law-firm",
        slug: "law-demo",
        displayName: "Legal Partners",
        category: "Service",
        industry: "services",
        businessModel: "Service",
        primaryUseCase: "Professional Services",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Trustworthy presence for professionals.",
            bullets: ["Practice areas", "Team bios", "Consultation form"],
            bestFor: ["Law Firms", "Accountants"],
            keyModules: ["Consultation Request", "Team Profiles"],
        },
        routes: ["/"],
        layoutKey: "StandardServiceHome",
        onboardingProfile: { prefill: { industryCategory: "services" } },
    },
    "vayva-clean-crew": {
        templateId: "vayva-clean-crew",
        slug: "clean-demo",
        displayName: "Clean Crew",
        category: "Service",
        industry: "services",
        businessModel: "Service",
        primaryUseCase: "Home Services",
        requiredPlan: "free",
        defaultTheme: "light",
        status: "active",
        preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
        compare: {
            headline: "Home services on demand.",
            bullets: ["Service selection", "Zip code check", "Recurring plans"],
            bestFor: ["Cleaners", "Plumbers", "Handymen"],
            keyModules: ["Location Check", "Subscriptions"],
        },
        routes: ["/"],
        layoutKey: "StandardServiceHome",
        onboardingProfile: { prefill: { industryCategory: "services" } },
    },
};
export function getNormalizedTemplates() {
    return Object.values(TEMPLATE_REGISTRY).filter((t: any) => t.status !== "deprecated");
}
export const TEMPLATE_CATEGORIES = [
    { slug: "fashion-clothing", displayName: "Fashion", isActive: true },
    { slug: "electronics-gadgets", displayName: "Electronics", isActive: true },
    { slug: "beauty-wellness-home", displayName: "Beauty & Home", isActive: true },
    { slug: "food-restaurant", displayName: "Food & Drink", isActive: true },
    { slug: "services-appointments", displayName: "Services", isActive: true },
    { slug: "digital-products", displayName: "Digital", isActive: true },
    { slug: "events-ticketing", displayName: "Events", isActive: true },
    { slug: "education-courses", displayName: "Education", isActive: true },
    { slug: "wholesale-b2b", displayName: "Wholesale (B2B)", isActive: true },
    { slug: "marketplace", displayName: "Marketplace", isActive: true },
    { slug: "donations-fundraising", displayName: "Non-profit", isActive: true },
    { slug: "real-estate", displayName: "Real Estate", isActive: true },
].map(c => ({
    ...c,
    // Helper to find templates for this category
    recommendedTemplates: Object.values(TEMPLATE_REGISTRY)
        .filter(t => t.industry === c.slug)
        .map(t => t.templateId)
}));
export function getTemplatesByCategory(categorySlug: any) {
    return Object.values(TEMPLATE_REGISTRY).filter(t => t.industry === categorySlug);
}
