"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CreditCard, Calendar, RefreshCw } from "lucide-react";
import { useOpsQuery } from "@/hooks/useOpsQuery";
import { Button } from "@vayva/ui";
export default function BillingPage() {
    const { data: subs, isLoading, refetch } = useOpsQuery(["billing-subs"], () => fetch("/api/ops/financials/subscriptions").then(res => res.json().then(j => j.data)));
    return (_jsxs("div", { className: "p-8 space-y-6", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { children: [_jsxs("h1", { className: "text-3xl font-bold text-gray-900 flex items-center gap-3", children: [_jsx(CreditCard, { className: "w-8 h-8 text-indigo-600" }), "Billing Monitor"] }), _jsx("p", { className: "text-gray-500 mt-1", children: "Track active SaaS subscriptions and revenue." })] }), _jsx(Button, { variant: "ghost", size: "icon", onClick: () => refetch(), className: "rounded-full h-8 w-8", "aria-label": "Refresh billing subscriptions", children: _jsx(RefreshCw, { className: `w-5 h-5 text-gray-500 ${isLoading ? 'animate-spin' : ''}` }) })] }), _jsx("div", { className: "bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden", children: _jsxs("table", { className: "w-full text-left text-sm", children: [_jsx("thead", { className: "bg-gray-50 text-gray-500 border-b border-gray-100", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 font-medium", children: "Store" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Plan" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Status" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Provider" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Renews" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-100", children: isLoading ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "p-12 text-center text-gray-400", children: "Loading subscriptions..." }) })) : !subs?.length ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "p-12 text-center text-gray-400", children: "No active subscriptions." }) })) : (subs.map((s) => (_jsxs("tr", { className: "hover:bg-gray-50", children: [_jsx("td", { className: "px-6 py-4 font-medium text-gray-900", children: s.store?.name || "Unknown Store" }), _jsx("td", { className: "px-6 py-4 font-mono text-xs text-purple-600 font-bold", children: s.planKey }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: `px-2 py-0.5 rounded text-xs font-bold ${s.status === "ACTIVE" ? "bg-green-100 text-green-700" :
                                                s.status === "TRIALING" ? "bg-blue-100 text-blue-700" : "bg-red-100 text-red-700"}`, children: s.status }) }), _jsx("td", { className: "px-6 py-4 text-gray-500 text-xs", children: s.provider }), _jsxs("td", { className: "px-6 py-4 flex items-center gap-1 text-gray-600", children: [_jsx(Calendar, { size: 14, className: "text-gray-400" }), new Date(s.currentPeriodEnd).toLocaleDateString()] })] }, s.id)))) })] }) })] }));
}
