import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@vayva/ui";
export function UpgradePlanModal({ isOpen, onClose, currentPlan, requiredPlan, }) {
    if (!isOpen)
        return null;
    // Display formatted name (e.g. growth -> Growth)
    const reqCap = requiredPlan.charAt(0).toUpperCase() + requiredPlan.slice(1);
    return (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4", children: _jsxs("div", { className: "bg-white rounded-2xl w-full max-w-md p-6 shadow-2xl relative animate-in fade-in zoom-in-95 duration-200", children: [_jsxs(Button, { onClick: onClose, className: "absolute top-4 right-4 text-gray-400 hover:text-gray-600", children: [_jsx("span", { className: "sr-only", children: "Close" }), _jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M6 18L18 6M6 6l12 12" }) })] }), _jsxs("div", { className: "text-center pt-2", children: [_jsx("div", { className: "w-16 h-16 bg-blue-50 rounded-full flex items-center justify-center mx-auto mb-4 text-blue-600", children: _jsx("svg", { className: "w-8 h-8", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M13 10V3L4 14h7v7l9-11h-7z" }) }) }), _jsxs("h2", { className: "text-2xl font-bold text-gray-900 mb-2", children: ["Upgrade to ", reqCap] }), _jsxs("p", { className: "text-gray-600 mb-8 px-4", children: ["To use this premium template, you need to be on the", " ", _jsx("strong", { children: reqCap }), " plan."] }), _jsxs("div", { className: "space-y-3", children: [_jsx(Button, { onClick: () => (window.location.href = "/dashboard/settings/billing"), className: "w-full py-3.5 bg-black text-white rounded-xl font-bold hover:bg-gray-800 transition-all shadow-lg hover:shadow-xl transform hover:-translate-y-0.5", children: "Upgrade Now" }), _jsx(Button, { onClick: onClose, className: "w-full py-3 text-gray-500 font-semibold hover:text-gray-800 transition-colors", children: "Maybe Later" })] })] })] }) }));
}
