import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useRouter } from "next/navigation";
import { Pagination } from "@/components/Pagination";
import { StatusChip, Icon } from "@vayva/ui";
export function ProductsTable({ products, meta, page, limit, onPageChange }) {
    const router = useRouter();
    const totalPages = meta ? Math.ceil(meta.total / limit) : 1;
    return (_jsxs("div", { className: "bg-white rounded-3xl shadow-xl shadow-black/5 border border-studio-border overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500", children: [_jsxs("table", { className: "w-full text-left text-sm", children: [_jsx("thead", { className: "bg-studio-gray text-gray-500 font-bold border-b border-studio-border uppercase tracking-widest text-[10px]", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-4", children: "Product" }), _jsx("th", { className: "px-6 py-4", children: "Price" }), _jsx("th", { className: "px-6 py-4", children: "Status" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-100", children: products.map((p) => (_jsxs("tr", { className: "hover:bg-studio-gray transition-colors cursor-pointer group border-b border-studio-border last:border-0", onClick: () => router.push(`/dashboard/products/${p.id}`), children: [_jsx("td", { className: "px-6 py-4", children: _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "w-14 h-14 bg-studio-gray rounded-2xl overflow-hidden border border-studio-border shrink-0 group-hover:scale-105 group-hover:rotate-2 transition-all duration-300", children: p.image ? (_jsx("img", { src: p.image, alt: p.name, className: "w-full h-full object-cover" })) : (_jsx("div", { className: "w-full h-full flex items-center justify-center", children: _jsx(Icon, { name: "Package", size: 20, className: "text-gray-300" }) })) }), _jsx("span", { className: "font-black text-vayva-black text-base group-hover:translate-x-1 transition-transform", children: p.name })] }) }), _jsx("td", { className: "px-6 py-4", children: _jsxs("span", { className: "font-mono font-black text-vayva-black", children: [p.currency, " ", p.price.toLocaleString()] }) }), _jsx("td", { className: "px-6 py-4", children: _jsx(StatusChip, { status: p.status }) })] }, p.id))) })] }), meta && totalPages > 1 && (_jsx("div", { className: "p-4 bg-gray-50/30 border-t border-gray-100", children: _jsx(Pagination, { currentPage: page, totalPages: totalPages, totalItems: meta.total, itemsPerPage: limit, onPageChange: onPageChange, showItemsPerPage: false }) }))] }));
}
