"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NIGERIAN_STATES } from "@/lib/i18n/addressNG";
import { COPY } from "@/lib/i18n/copy";
export function AddressInputNG({ value, onChange, errors, }) {
    const handleChange = (field, val) => {
        onChange({ ...value, [field]: val });
    };
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-xs font-bold uppercase text-gray-500 mb-1", children: "Address Line 1" }), _jsx("input", { value: value?.addressLine1 || "", onChange: (e) => handleChange("addressLine1", e.target.value), className: "w-full border p-2 rounded", placeholder: "123 Street Name" }), errors?.addressLine1 && (_jsx("p", { className: "text-red-500 text-xs mt-1", children: errors.addressLine1 }))] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-xs font-bold uppercase text-gray-500 mb-1", children: COPY.STATE_LABEL }), _jsxs("select", { value: value?.state || "", onChange: (e) => handleChange("state", e.target.value), className: "w-full border p-2 rounded bg-white", children: [_jsx("option", { value: "", children: "Select State" }), NIGERIAN_STATES.map((s) => (_jsx("option", { value: s, children: s }, s)))] }), errors?.state && (_jsx("p", { className: "text-red-500 text-xs mt-1", children: errors.state }))] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-bold uppercase text-gray-500 mb-1", children: COPY.LGA_LABEL }), _jsx("input", { value: value?.city || "", onChange: (e) => handleChange("city", e.target.value), className: "w-full border p-2 rounded", placeholder: "e.g. Ikeja" }), errors?.city && (_jsx("p", { className: "text-red-500 text-xs mt-1", children: errors.city }))] })] }), _jsxs("div", { children: [_jsxs("label", { className: "block text-xs font-bold uppercase text-gray-500 mb-1", children: [COPY.LANDMARK_LABEL, " ", _jsx("span", { className: "text-red-500", children: "*" })] }), _jsx("input", { value: value?.landmark || "", onChange: (e) => handleChange("landmark", e.target.value), className: "w-full border p-2 rounded", placeholder: COPY.LANDMARK_PLACEHOLDER }), errors?.landmark && (_jsx("p", { className: "text-red-500 text-xs mt-1", children: errors.landmark }))] })] }));
}
