import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Button } from "@vayva/ui";
import { Bed, Bath, Square, MapPin, Heart } from "lucide-react";
export const ListingCard = ({ product, onViewClick }) => {
    const details = product.propertyDetails;
    if (!details)
        return null;
    return (_jsxs("div", { className: "bg-white border border-gray-100 rounded-xl overflow-hidden hover:shadow-xl hover:-translate-y-1 transition-all duration-300 group cursor-pointer relative", children: [_jsxs("div", { className: "h-64 relative bg-gray-200 overflow-hidden", children: [_jsx("img", { src: product.images?.[0], alt: product.name, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" }), _jsxs("div", { className: "absolute top-4 left-4 flex gap-2", children: [_jsxs("span", { className: `px-3 py-1 rounded text-[10px] font-bold uppercase tracking-wide text-white shadow-sm ${details.purpose === "rent" ? "bg-[#2563EB]" : details.purpose === "sale" ? "bg-[#0F172A]" : "bg-[#F59E0B]"}`, children: ["For ", details.purpose] }), details.type === "land" && (_jsx("span", { className: "bg-[#16A34A] text-white px-3 py-1 rounded text-[10px] font-bold uppercase tracking-wide shadow-sm", children: "Land" }))] }), _jsx(Button, { className: "absolute top-4 right-4 w-8 h-8 rounded-full bg-white/90 backdrop-blur-sm flex items-center justify-center text-gray-400 hover:text-red-500 hover:scale-110 transition-all", children: _jsx(Heart, { size: 16, fill: false ? "currentColor" : "none" }) }), _jsx("div", { className: "absolute bottom-0 left-0 w-full bg-gradient-to-t from-black/60 to-transparent p-4 text-white", children: _jsxs("p", { className: "text-2xl font-black", children: ["\u20A6", product.price.toLocaleString(), details.purpose === "rent"
                                    ? "/yr"
                                    : details.purpose === "shortlet"
                                        ? "/night"
                                        : ""] }) })] }), _jsxs("div", { className: "p-5", children: [_jsx("div", { className: "flex items-start justify-between gap-4 mb-3", children: _jsx("h3", { className: "font-bold text-gray-900 text-lg leading-tight line-clamp-1 group-hover:text-[#2563EB] transition-colors", children: product.name }) }), _jsxs("div", { className: "flex items-center gap-1.5 text-gray-500 text-sm mb-6", children: [_jsx(MapPin, { size: 16, className: "text-[#2563EB]" }), _jsx("span", { className: "truncate", children: details.location })] }), _jsxs("div", { className: "flex items-center justify-between border-t border-gray-100 pt-4 text-gray-600 text-sm", children: [details.type !== "land" ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx(Bed, { size: 18, className: "text-gray-400" }), _jsx("span", { className: "font-bold text-gray-900", children: details.beds }), " ", "Beds"] }), _jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx(Bath, { size: 18, className: "text-gray-400" }), _jsx("span", { className: "font-bold text-gray-900", children: details.baths }), " ", "Baths"] })] })) : (_jsx("div", { className: "text-xs text-gray-400 font-bold uppercase", children: "Ready to build" })), details.sqm && (_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx(Square, { size: 18, className: "text-gray-400" }), _jsx("span", { className: "font-bold text-gray-900", children: details.sqm }), " sqm"] }))] }), onViewClick && (_jsx(Button, { onClick: (e) => {
                            e.stopPropagation();
                            onViewClick();
                        }, className: "w-full mt-5 bg-white border-2 border-gray-100 hover:border-[#2563EB] text-gray-700 hover:text-[#2563EB] font-bold py-2.5 rounded-lg transition-colors", children: "Schedule Viewing" }))] })] }));
};
