"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Link from "next/link";
import { motion } from "framer-motion";
import { Button, Icon } from "@vayva/ui";
import { PLANS, formatNGN, FEES } from "@/config/pricing";
import { APP_URL } from "@/lib/constants";
import { PlanComparisonTable } from "@/components/pricing/PlanComparisonTable";
import { PlanComparisonMobile } from "@/components/pricing/PlanComparisonMobile";
import { PremiumButton } from "@/components/marketing/PremiumButton";
import { useUserPlan } from "@/hooks/useUserPlan";
export default function PricingPage() {
    const { tier, isAuthenticated, loading } = useUserPlan();
    return (_jsxs("div", { className: "min-h-screen bg-white relative overflow-hidden", children: [_jsxs("div", { className: "absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0", children: [_jsx("div", { className: "absolute top-[-5%] right-[-5%] w-[40%] h-[40%] bg-blue-50 rounded-full blur-[120px] opacity-60 animate-pulse" }), _jsx("div", { className: "absolute bottom-[20%] left-[-10%] w-[35%] h-[35%] bg-green-50 rounded-full blur-[100px] opacity-40 animate-pulse delay-1000" })] }), _jsx("section", { className: "pt-24 pb-20 px-4 relative z-10", children: _jsxs("div", { className: "max-w-4xl mx-auto text-center", children: [_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, className: "inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 text-blue-600 text-[10px] font-black uppercase tracking-widest mb-6 border border-blue-100", children: "Transparent Pricing" }), _jsxs(motion.h1, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.1 }, className: "text-5xl md:text-7xl font-bold text-[#0F172A] mb-8 leading-[1.1] tracking-tight", children: ["Scale your business, ", _jsx("br", {}), "not your costs."] }), _jsx(motion.p, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.2 }, className: "text-xl text-[#64748B] max-w-2xl mx-auto mb-10 leading-relaxed", children: "Choose a plan that matches your volume. Every plan includes our core WhatsApp capture engine and local payment infrastructure." }), _jsx(motion.div, { initial: { opacity: 0, scale: 0.95 }, animate: { opacity: 1, scale: 1 }, transition: { delay: 0.3 }, className: "flex justify-center", children: _jsxs("div", { className: "inline-flex items-center gap-3 px-6 py-3 bg-red-50/50 backdrop-blur-md border border-red-100 rounded-2xl", children: [_jsx("div", { className: "w-8 h-8 rounded-full bg-red-100 flex items-center justify-center text-red-600 shrink-0", children: _jsx(Icon, { name: "Info", size: 18 }) }), _jsxs("p", { className: "text-sm font-bold text-red-900", children: ["Honest Disclosure: A ", FEES.WITHDRAWAL_PERCENTAGE, "% transaction fee is charged on every withdrawal."] })] }) })] }) }), _jsx("section", { className: "pb-32 px-4 relative z-10", children: _jsx("div", { className: "max-w-7xl mx-auto", children: _jsx("div", { className: "flex lg:grid lg:grid-cols-3 gap-6 lg:gap-8 overflow-visible overflow-x-auto pt-12 pb-12 lg:pb-0 px-4 -mx-4 lg:px-0 lg:mx-0 snap-x snap-mandatory scrollbar-hide", children: PLANS.map((plan, idx) => {
                            const isCurrentPlan = isAuthenticated && tier === plan.key;
                            let href = plan.monthlyAmount === 0
                                ? `${APP_URL}/signup`
                                : `${APP_URL}/signup?plan=${plan.key}`;
                            let label = plan.ctaLabel;
                            if (loading) {
                            }
                            else if (isAuthenticated) {
                                if (isCurrentPlan) {
                                    href = `${APP_URL}/settings/billing`;
                                    label = "Current Plan";
                                }
                                else {
                                    href = `${APP_URL}/settings/billing`;
                                    label = tier === "free" ? "Switch Plan" : (plan.monthlyAmount > 0 ? "Switch Plan" : "Downgrade");
                                }
                            }
                            return (_jsxs(motion.div, { initial: { opacity: 0, y: 30 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { delay: idx * 0.1 + 0.3 }, className: `relative flex flex-col p-8 lg:p-10 rounded-[40px] border transition-all duration-500 snap-center shrink-0 w-[85vw] lg:w-full ${isCurrentPlan
                                    ? "border-blue-500 shadow-[0_32px_64px_-16px_rgba(59,130,246,0.15)] ring-4 ring-blue-50 bg-blue-50/10"
                                    : plan.featured
                                        ? "border-[#22C55E] shadow-[0_32px_64px_-16px_rgba(34,197,94,0.15)] ring-4 ring-green-50"
                                        : "border-gray-100 shadow-[0_20px_40px_-15px_rgba(0,0,0,0.05)]"} bg-white hover:translate-y-[-4px]`, children: [plan.featured && !isCurrentPlan && (_jsx("div", { className: "absolute -top-4 left-1/2 -translate-x-1/2 bg-[#22C55E] text-white text-[10px] font-black uppercase tracking-widest px-6 py-2 rounded-full shadow-[0_10px_20px_-5px_rgba(34,197,94,0.4)]", children: "Most Popular" })), isCurrentPlan && (_jsx("div", { className: "absolute -top-4 left-1/2 -translate-x-1/2 bg-blue-500 text-white text-[10px] font-black uppercase tracking-widest px-6 py-2 rounded-full shadow-[0_10px_20px_-5px_rgba(59,130,246,0.4)]", children: "Your Plan" })), _jsxs("div", { className: "mb-8", children: [_jsx("h3", { className: "text-2xl lg:text-3xl font-bold text-[#0F172A] mb-3 tracking-tight", children: plan.name }), _jsx("p", { className: "text-sm text-[#64748B] font-medium leading-relaxed", children: plan.tagline })] }), _jsxs("div", { className: "mb-8", children: [_jsxs("div", { className: "flex items-baseline gap-1", children: [_jsx("span", { className: "text-5xl lg:text-6xl font-bold text-[#0F172A] tracking-tighter", children: formatNGN(plan.baseAmount) }), plan.baseAmount > 0 && (_jsx("span", { className: "text-[#64748B] text-lg font-semibold", children: "/mo" }))] }), plan.vatAmount > 0 && (_jsxs("p", { className: "text-[10px] font-bold text-[#64748B] mt-2 uppercase tracking-widest", children: ["+ ", formatNGN(plan.vatAmount), " VAT (", formatNGN(plan.monthlyAmount), " total)"] })), plan.trialDays && !isAuthenticated && (_jsxs("p", { className: "text-xs font-bold text-[#22C55E] mt-3 uppercase tracking-wider", children: ["Includes ", plan.trialDays, " days free trial"] }))] }), _jsx("ul", { className: "space-y-5 mb-12 flex-grow", children: plan.bullets.map((bullet, i) => (_jsxs("li", { className: "flex items-start gap-3 group/item", children: [_jsx("div", { className: "mt-1 w-5 h-5 rounded-full bg-green-50 flex items-center justify-center shrink-0 group-hover/item:scale-110 transition-transform", children: _jsx("svg", { className: "w-3 h-3 text-[#22C55E]", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 3, d: "M5 13l4 4L19 7" }) }) }), _jsx("span", { className: "text-sm font-medium text-[#475569]", children: bullet })] }, i))) }), _jsx(Link, { href: href, className: "block mt-auto", children: plan.featured || isCurrentPlan ? (_jsx(PremiumButton, { disabled: isCurrentPlan, className: `w-full py-8 text-lg rounded-[24px] ${isCurrentPlan ? "opacity-90 grayscale-[0.5]" : "shadow-[0_20px_40px_-10px_rgba(34,197,94,0.3)]"}`, children: label })) : (_jsx(Button, { className: `w-full py-8 text-lg font-bold rounded-[24px] transition-all hover:scale-[1.02] bg-[#0F172A] hover:bg-black text-white`, children: label })) })] }, plan.key));
                        }) }) }) }), _jsx("section", { className: "py-32 px-4 bg-gray-50/50 relative overflow-hidden", children: _jsxs("div", { className: "max-w-6xl mx-auto relative z-10", children: [_jsxs("div", { className: "text-center mb-20", children: [_jsx("div", { className: "inline-flex items-center gap-2 px-3 py-1 rounded-full bg-slate-100 text-slate-600 text-[10px] font-black uppercase tracking-widest mb-6 border border-slate-200", children: "Detailed Breakdown" }), _jsx("h2", { className: "text-4xl md:text-5xl font-bold text-[#0F172A] mb-4 tracking-tight", children: "Compare every detail." }), _jsx("p", { className: "text-[#64748B] text-lg", children: "No hidden limits. See exactly what you get on each tier." })] }), _jsx("div", { className: "lg:hidden", children: _jsx(PlanComparisonMobile, {}) }), _jsx("div", { className: "hidden lg:block", children: _jsx(PlanComparisonTable, {}) }), _jsx("div", { className: "mt-16 p-8 bg-white/80 backdrop-blur-md border border-gray-100 rounded-[32px] shadow-sm text-center", children: _jsxs("p", { className: "text-sm font-bold text-[#64748B] flex items-center justify-center gap-3", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-red-500 animate-pulse" }), "Note: All plans are subject to a ", FEES.WITHDRAWAL_PERCENTAGE, "% transaction fee on every withdrawal from your Vayva Wallet."] }) })] }) }), _jsx("section", { className: "py-32 px-4 relative z-10", children: _jsxs("div", { className: "max-w-4xl mx-auto", children: [_jsxs("div", { className: "text-center mb-16", children: [_jsx("h2", { className: "text-4xl font-bold text-[#0F172A] mb-4 tracking-tight", children: "Frequently Asked Questions" }), _jsx("p", { className: "text-[#64748B]", children: "Everything you need to know about Vayva pricing." })] }), _jsx("div", { className: "grid md:grid-cols-2 gap-6", children: [
                                {
                                    q: "How does the 7-day trial work?",
                                    a: "You get full access to all features for 7 days. No credit card required. If you don't subscribe after the trial, your account will be paused.",
                                },
                                {
                                    q: "When is the withdrawal fee charged?",
                                    a: "The 3% fee is deducted only when you move money from your Vayva Wallet to your external bank account. No fees for incoming payments.",
                                },
                                {
                                    q: "Can I cancel any time?",
                                    a: "Yes. Vayva is month-to-month. You can cancel, upgrade, or downgrade your plan instantly from your dashboard.",
                                },
                                {
                                    q: "Are there transaction fees?",
                                    a: "Vayva doesn't charge per-transaction fees. You only pay your monthly subscription and the withdrawal fee when moving cash out.",
                                },
                            ].map((faq, i) => (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { delay: i * 0.1 }, className: "p-8 bg-gray-50/50 rounded-[32px] border border-gray-100 hover:bg-white hover:shadow-xl transition-all", children: [_jsx("h4", { className: "font-bold text-[#0F172A] mb-3 text-lg", children: faq.q }), _jsx("p", { className: "text-sm text-[#64748B] leading-relaxed", children: faq.a })] }, i))) })] }) })] }));
}
