"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Zap, Clock, RefreshCw } from "lucide-react";
import { useOpsQuery } from "@/hooks/useOpsQuery";
import { Button } from "@vayva/ui";
export default function CampaignsPage() {
    const { data: campaigns, isLoading, refetch } = useOpsQuery(["active-campaigns"], () => fetch("/api/ops/growth/campaigns/active").then(res => res.json().then(j => j.data)));
    return (_jsxs("div", { className: "p-8 space-y-6", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { children: [_jsxs("h1", { className: "text-3xl font-bold text-gray-900 flex items-center gap-3", children: [_jsx(Zap, { className: "w-8 h-8 text-amber-500" }), "Live Campaigns"] }), _jsx("p", { className: "text-gray-500 mt-1", children: "Real-time monitor of active merchant flash sales." })] }), _jsx(Button, { variant: "ghost", size: "icon", onClick: () => refetch(), className: "rounded-full h-8 w-8", "aria-label": "Refresh active campaigns", children: _jsx(RefreshCw, { className: `w-5 h-5 text-gray-500 ${isLoading ? 'animate-spin' : ''}` }) })] }), _jsx("div", { className: "bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden", children: _jsxs("table", { className: "w-full text-left text-sm", children: [_jsx("thead", { className: "bg-gray-50 text-gray-500 border-b border-gray-100", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 font-medium", children: "Campaign Name" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Merchant" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Discount" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Target" }), _jsx("th", { className: "px-6 py-3 font-medium", children: "Ends In" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-100", children: isLoading ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "p-12 text-center text-gray-400", children: "Loading campaigns..." }) })) : !campaigns?.length ? (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "p-12 text-center text-gray-400", children: "No active campaigns." }) })) : (campaigns.map((c) => {
                                const end = new Date(c.endTime);
                                const now = new Date();
                                const diff = Math.max(0, Math.ceil((end.getTime() - now.getTime()) / (1000 * 60 * 60))); // Hours
                                return (_jsxs("tr", { className: "hover:bg-gray-50", children: [_jsx("td", { className: "px-6 py-4 font-medium text-gray-900", children: c.name }), _jsx("td", { className: "px-6 py-4 text-gray-600", children: c.store?.name }), _jsx("td", { className: "px-6 py-4", children: _jsxs("span", { className: "bg-red-100 text-red-700 px-2 py-0.5 rounded text-xs font-bold", children: ["-", c.discount, "%"] }) }), _jsx("td", { className: "px-6 py-4 text-xs font-mono text-gray-500", children: c.targetType }), _jsxs("td", { className: "px-6 py-4 flex items-center gap-1 text-amber-600 font-medium", children: [_jsx(Clock, { size: 14 }), diff, " hours"] })] }, c.id));
                            })) })] }) })] }));
}
